# **ST 554 Spring 2026 Project Two**
## Created by Cody Ashby on March 17, 2026
### *Testing a Customized Class on a Data Set (Part I)*
#### *** NOT FINALIZED! ***

To start things off, we'll use a class that performs a quality check for a Spark SQL style dataframe. A handful of modules will need to be imported before implementing this class.

In [ ]:
#from pyspark.sql import DataFrame
#from pyspark.sql import functions as F
#from functools import reduce
#from pyspark.sql.types import *
#import pandas as pd

Before proceeding, we'll need to initiate a Spark session.

In [1]:
#from pyspark.sql import SparkSession
#spark = SparkSession.builder.master('local[*]').appName('my_app').getOrCreate()

WARNING: Using incubator modules: jdk.incubator.vector
Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
26/03/20 17:55:58 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable

Now, we'll import the Python file that contains the class so we can do our quality check.

In [ ]:
#import SparkDataQualityCheck.py

We'll use the method that reads in a csv file, namely the air quality data set from our first project, to try this out.

### *Practicing pandas-on-spark and Spark SQL on NFL Data (Part II)*
#### *** IN PROGRESS ***

In this portion, we'll utilize `pandas-on-spark` and Spark SQL techniques to perform some basic data analysis on an NFL data set. We'll use the former to read in this data set first.

In [3]:
import pandas as pd
import numpy as np
import pyspark.pandas as ps
from pyspark.sql import SparkSession
spark = SparkSession.builder.master('local[*]').appName('ST 554 Project Two').config('spark.sql.ansi.enabled','false').getOrCreate()

/opt/tljh/user/envs/pySpark3/lib/python3.9/site-packages/pyspark/pandas/__init__.py:43: UserWarning: 'PYARROW_IGNORE_TIMEZONE' environment variable was not set. It is required to set this environment variable to '1' in both driver and executor sides if you use pyarrow>=2.0.0. pandas-on-Spark will set it for you but it does not work if there is a Spark context already launched.
  warnings.warn(
WARNING: Using incubator modules: jdk.incubator.vector
Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
26/03/20 22:23:41 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
26/03/20 22:23:41 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
26/03/20 22:23:41 WARN Utils: Service 'SparkUI' could not bind on port 4041. Attempting port 4042.
26/03/20 22:23:41 WARN Utils: Service 'SparkUI' could not bind on port 4042. Attempting port 4043.
26/03/20 22:23:41 WARN Utils: Service 'SparkUI' could not bind on port 4043. Attempting port 4044.
26/03/20 22:23:41 WARN Utils: Service 'SparkUI' could not bind on port 4044. Attempting port 4045.

Now, we'll use `pandas` to read in the data set.

In [4]:
NFL_data=pd.read_csv("weekly_nfl_data.csv")
spark_NFL_data=ps.from_pandas(NFL_data)
spark_NFL_data.head()

26/03/20 22:23:51 WARN SparkStringUtils: Truncated the string representation of a plan since it was too large. This behavior can be adjusted by setting 'spark.sql.debug.maxToStringFields'.

    player_id player_name    player_display_name position position_group headshot_url recent_team  season  week season_type opponent_team  completions  attempts  passing_yards  passing_tds  interceptions  sacks  sack_yards  sack_fumbles  sack_fumbles_lost  passing_air_yards  passing_yards_after_catch  passing_first_downs  passing_epa  passing_2pt_conversions  pacr  dakota  carries  rushing_yards  rushing_tds  rushing_fumbles  rushing_fumbles_lost  rushing_first_downs  rushing_epa  rushing_2pt_conversions  receptions  targets  receiving_yards  receiving_tds  receiving_fumbles  receiving_fumbles_lost  receiving_air_yards  receiving_yards_after_catch  receiving_first_downs  receiving_epa  receiving_2pt_conversions  racr  target_share  air_yards_share  wopr  special_teams_tds  fantasy_points  fantasy_points_ppr
0  00-0000003        None  Abdul-Karim al-Jabbar       RB             RB         None         MIA    1999     1         REG           DEN            0         0            0.0            0            0.0    0.0         0.0             0                  0                0.0                        0.0                  0.0          NaN                        0   NaN     NaN       16           60.0            1              0.0                   0.0                  4.0     6.248771                        0           1        1              7.0              0                0.0                     0.0                  0.0                          0.0                    0.0       0.292378                          0   0.0      0.052632              NaN   NaN                0.0            12.7                13.7
1  00-0000003        None  Abdul-Karim al-Jabbar       RB             RB         None         MIA    1999     2         REG           ARI            0         0            0.0            0            0.0    0.0         0.0             0                  0                0.0                        0.0                  0.0          NaN                        0   NaN     NaN        9           33.0            0              0.0                   0.0                  1.0    -1.434950                        0           3        4             18.0              0                0.0                     0.0                  0.0                          0.0                    1.0       0.377009                          0   0.0      0.117647              NaN   NaN                0.0             5.1                 8.1
2  00-0000003        None  Abdul-Karim al-Jabbar       RB             RB         None         MIA    1999     4         REG           BUF            0         0            0.0            0            0.0    0.0         0.0             0                  0                0.0                        0.0                  0.0          NaN                        0   NaN     NaN        3            2.0            0              0.0                   0.0                  0.0    -1.539952                        0           0        1              0.0              0                0.0                     0.0                  0.0                          0.0                    0.0      -0.699578                          0   NaN      0.023810              NaN   NaN                0.0             0.2                 0.2
3  00-0000003        None  Abdul-Karim al-Jabbar       RB             RB         None         CLE    1999     7         REG            LA            0         0            0.0            0            0.0    0.0         0.0             0                  0                0.0                        0.0                  0.0          NaN                        0   NaN     NaN        6           27.0            0              0.0                   0.0                  0.0     0.216051                        0           2        2              8.0              0                0.0                     0.0                  0.0                          0.0                    0.0      -0.228454                          0   0.0      0.050000              NaN   NaN                0.0             3.5                 5.5
4  00-0000003        None  Abdul-Karim al-Jabbar       RB             RB         None         CLE    1999     8         REG            NO            0         0            0.0            0            0.0    0.0         0.0             0                  0                0.0                        0.0                  0.0          NaN                        0   NaN     NaN       13           39.0            0              0.0                   0.0                  2.0    -2.972259                        0           0        0              0.0              0                0.0                     0.0                  0.0                          0.0                    0.0            NaN                          0   NaN           NaN              NaN   NaN                0.0             3.9                 3.9

Below is a list of the column names.

In [5]:
spark_NFL_data.columns

Index(['player_id', 'player_name', 'player_display_name', 'position',
       'position_group', 'headshot_url', 'recent_team', 'season', 'week',
       'season_type', 'opponent_team', 'completions', 'attempts',
       'passing_yards', 'passing_tds', 'interceptions', 'sacks', 'sack_yards',
       'sack_fumbles', 'sack_fumbles_lost', 'passing_air_yards',
       'passing_yards_after_catch', 'passing_first_downs', 'passing_epa',
       'passing_2pt_conversions', 'pacr', 'dakota', 'carries', 'rushing_yards',
       'rushing_tds', 'rushing_fumbles', 'rushing_fumbles_lost',
       'rushing_first_downs', 'rushing_epa', 'rushing_2pt_conversions',
       'receptions', 'targets', 'receiving_yards', 'receiving_tds',
       'receiving_fumbles', 'receiving_fumbles_lost', 'receiving_air_yards',
       'receiving_yards_after_catch', 'receiving_first_downs', 'receiving_epa',
       'receiving_2pt_conversions', 'racr', 'target_share', 'air_yards_share',
       'wopr', 'special_teams_tds', 'fantasy_points', 'fantasy_points_ppr'],
      dtype='object')

Now, we'll collect some statistics involving quarterback players during the regular season from 2005 to 2023. Namely, we're interested in who the quarterback players are (of course), the season, the week in the season, and the number of completions, attempts, passing yards, passing touchdowns, and interceptions.

First, we'll do a sum of the numerical variables that's grouped by the player and season.

In [11]:
QB_table=spark_NFL_data.loc[((spark_NFL_data.position == "QB") & (spark_NFL_data.season > 2004) & (spark_NFL_data.season_type == "REG")), ['player_display_name', 'season', 'week', 'completions', 'attempts', 'passing_yards', 'passing_tds', 'interceptions']]
sum_QB_stats=QB_table.groupby(['player_display_name','season']).sum()
sum_QB_stats

                            week  completions  attempts  passing_yards  passing_tds  interceptions
player_display_name season
Jeff Blake          2005      19            8         9           55.0            1            0.0
Daunte Culpepper    2005      31          139       216         1564.0            6           12.0
Kerry Collins       2005     134          302       566         3759.0           20           13.0
Tony Banks          2005      17           14        25          173.0            1            2.0
Charlie Batch       2005      35           23        36          246.0            1            1.0
Jeff Garcia         2005      69          102       173          937.0            3            6.0
Doug Flutie         2005      54            5        10           29.0            0            0.0
Brett Favre         2005     147          372       607         3881.0           20           29.0
Todd Bouman         2005      60           68       122          722.0            2            7.0
Brad Johnson        2005     131          183       293         1885.0           12            4.0
Brian Griese        2005      21          112       174         1136.0            7            7.0
Gus Frerotte        2005     149          257       494         2996.0           18           13.0
Kelly Holcomb       2005      90          155       230         1509.0           10            8.0
Mark Brunell        2005     150          262       454         3050.0           23           10.0
Jay Fiedler         2005       4            8        13          107.0            1            0.0
Koy Detmer          2005      53           32        56          238.0            0            3.0
Jake Delhomme       2005     146          262       435         3421.0           24           16.0
Aaron Brooks        2005      95          240       431         2882.0           13           17.0
Trent Dilfer        2005      74          199       333         2321.0           11           12.0
Trent Green         2005     148          317       507         4014.0           17           10.0
Drew Bledsoe        2005     144          300       499         3639.0           23           17.0
Todd Collins        2005      11            0         0            0.0            0            0.0
Matt Hasselbeck     2005     145          294       450         3455.0           24           10.0
Tim Hasselbeck      2005       1            0         0            0.0            0            0.0
Tim Rattay          2005      10           56        97          667.0            5            6.0
Kordell Stewart     2005       9            0         0            0.0            0            0.0
Jon Kitna           2005      48           17        29           99.0            0            2.0
Tom Brady           2005     146          334       530         4110.0           26           14.0
Steve McNair        2005     119          292       476         3161.0           16           11.0
Jamie Martin        2005      92          124       177         1277.0            5            7.0
Peyton Manning      2005     145          305       453         3747.0           28           10.0
Chad Pennington     2005       6           49        83          530.0            2            3.0
Marc Bulger         2005      42          192       287         2297.0           14            9.0
Donovan McNabb      2005      49          211       357         2507.0           16            9.0
Anthony Wright      2005      42          164       266         1582.0            6            9.0
Billy Volek         2005      54           50        88          474.0            4            2.0
Vinny Testaverde    2005      54           60       106          777.0            1            6.0
Kurt Warner         2005      90          242       375         2713.0           11            9.0
Jake Plummer        2005     144          277       456         3366.0           18            7.0
Tommy Maddox        2005      27           34        71          406.0            2            4.0
David Garrard       2005      98           98       168         1117.0            4            1.0
David Carr          2005     150          256       423         2488.0           14           11.0
Josh McCown         2005      76          163       270         1832.0            9           11.0
Shaun Hill          2005      17            0         0            0.0            0            0.0
Mike McMahon        2005     110           94       207         1158.0            5            8.0
Drew Brees          2005     143          323       500         3576.0           24           15.0
Mike Vick           2005     140          214       387         2412.0           15           13.0
Quinn Gray          2005      17            8        14          100.0            2            0.0
Chris Weinke        2005      31            7        13           64.0            1            0.0
Marques Tuiasosopo  2005      14           14        26          124.0            1            2.0
Joey Harrington     2005     108          188       330         2021.0           12           12.0
Sage Rosenfels      2005      46           34        61          462.0            4            3.0
Rex Grossman        2005      31           20        39          259.0            1            2.0
Kyle Boller         2005     109          171       293         1799.0           11           12.0
Jim Sorgi           2005      57           43        62          444.0            3            1.0
Ken Dorsey          2005      31           48        90          481.0            2            2.0
Seneca Wallace      2005      53           13        25          173.0            1            1.0
Brooks Bollinger    2005     128          150       266         1558.0            7            6.0
Kliff Kingsbury     2005      11            1         2           17.0            0            0.0
Patrick Ramsey      2005      32           15        25          279.0            1            1.0
Carson Palmer       2005     143          345       509         3836.0           32           12.0
Tony Romo           2005       5            0         0            0.0            0            0.0
Chris Simms         2005     131          191       313         2035.0           10            7.0
Cody Pickett        2005      27           14        35          140.0            0            2.0
Byron Leftwich      2005      71          175       302         2123.0           15            5.0
Drew Bledsoe        2006      25           90       169         1164.0            7            8.0
Bradlee Van Pelt    2005      30            2         8            7.0            0            0.0
J.P. Losman         2005      70          114       228         1340.0            8            8.0
Philip Rivers       2005      28           12        22          115.0            0            1.0
Ryan Fitzpatrick    2005      54           76       135          777.0            4            8.0
Matt Mauck          2005      24           15        27          136.0            0            1.0
Ben Roethlisberger  2005     113          168       268         2385.0           17            9.0
John Navarre        2005      15           14        24          174.0            1            1.0
Kerry Collins       2006       6           42        90          549.0            1            6.0
Matt Schaub         2005      65           33        64          495.0            4            0.0
Mark Brunell        2006      64          162       261         1789.0            8            4.0
Kyle Orton          2005     133          190       368         1869.0            9           13.0
Charlie Batch       2006      71           30        52          477.0            5            0.0
Alex Smith          2005      93           84       165          875.0            1           11.0
Dan Orlovsky        2005      14            7        17           63.0            0            0.0
Aaron Rodgers       2005      37            9        16           65.0            0            1.0
Eli Manning         2005     148          294       558         3762.0           24           17.0
Charlie Frye        2005      98           98       165         1002.0            4            6.0
Aaron Brooks        2006      85          110       192         1105.0            3            8.0
Matt Cassel         2005      21           13        24          183.0            2            1.0
Peyton Manning      2006     147          362       557         4397.0           31            9.0
Trent Green         2006      99          121       198         1342.0            7            9.0
Steve McNair        2006     146          295       468         3050.0           16           12.0
Daunte Culpepper    2006      10           81       134          929.0            2            3.0
Kurt Warner         2006      43          108       168         1377.0            6            5.0
Jake Plummer        2006      91          175       317         1994.0           11           13.0
Jon Kitna           2006     145          372       596         4208.0           21           22.0
Billy Volek         2006      17            1         2            4.0            0            0.0
Damon Huard         2006      69          148       244         1878.0           11            1.0
Gus Frerotte        2006      12            1         3           27.0            0            0.0
Jeff Garcia         2006     102          116       188         1309.0           10            2.0
Brad Johnson        2006     131          270       439         2750.0           10           15.0
Vinny Testaverde    2006      43            2         3           29.0            1            0.0
Brett Favre         2006     147          343       613         3885.0           18           18.0
Donovan McNabb      2006      57          180       316         2612.0           18            6.0
Jamie Martin        2006      17           16        24          208.0            1            1.0
Anthony Wright      2006      26            3         3           31.0            0            0.0
Matt Hasselbeck     2006     110          210       371         2442.0           18           15.0
Jake Delhomme       2006      99          263       431         2805.0           17           11.0
Brian Griese        2006      48           18        32          220.0            1            2.0
Cleo Lemon          2006      60           38        68          412.0            2            1.0
Marc Bulger         2006     146          370       588         4301.0           24            8.0
Tim Rattay          2006      62           61       101          748.0            4            2.0
A.J. Feeley         2006      29           26        38          342.0            3            0.0
David Carr          2006     148          302       442         2765.0           11           12.0
Sage Rosenfels      2006      24           27        39          265.0            3            1.0
Tom Brady           2006     147          320       517         3533.0           24           12.0
Joey Harrington     2006     118          223       388         2236.0           12           15.0
Marques Tuiasosopo  2006      12            6        13           68.0            1            2.0
Drew Brees          2006     146          357       555         4424.0           26           11.0
Chris Weinke        2006      45           56        96          625.0            2            4.0
Chad Pennington     2006     144          313       485         3352.0           17           16.0
Mike Vick           2006     148          205       389         2474.0           20           13.0
Quinn Gray          2006      17           13        22          166.0            0            0.0
Seneca Wallace      2006      49           82       141          927.0            8            7.0
Jared Lorenzen      2006      17            0         0            0.0            0            0.0
Ken Dorsey          2006      16            0         1            0.0            0            0.0
Chris Simms         2006       6           58       106          585.0            1            7.0
Rex Grossman        2006     146          262       480         3197.0           23           20.0
Patrick Ramsey      2006      12            0         1            0.0            0            0.0
Brooks Bollinger    2006      21           13        18          146.0            0            1.0
Byron Leftwich      2006      22          109       184         1158.0            7            5.0
Carson Palmer       2006     148          324       520         4036.0           28           13.0
Tony Romo           2006     142          220       337         2903.0           19           13.0
Josh McCown         2006      13            0         0            0.0            0            0.0
Kyle Boller         2006      34           33        55          485.0            5            2.0
David Garrard       2006     125          145       241         1735.0           10            9.0
Jason Campbell      2006      98          110       207         1297.0           10            6.0
Matt Schaub         2006      60           18        27          208.0            1            2.0
Philip Rivers       2006     150          284       460         3387.0           22            9.0
J.P. Losman         2006     145          269       430         3050.0           19           14.0
Aaron Rodgers       2006      15            6        15           46.0            0            0.0
Brett Basanez       2006      15            6        11           56.0            0            1.0
Derek Anderson      2006      58           66       117          793.0            5            8.0
Ryan Fitzpatrick    2006      17            0         0            0.0            0            0.0
Eli Manning         2006     149          301       522         3244.0           25           18.0
Ben Roethlisberger  2006     148          281       470         3528.0           18           23.0
Charlie Frye        2006     102          251       391         2449.0           10           17.0
Matt Cassel         2006      65            5         8           32.0            0            0.0
Alex Smith          2006     146          259       443         2901.0           16           15.0
Andrew Walter       2006      94          147       276         1677.0            3           13.0
Trent Dilfer        2007      66          113       219         1166.0            7           12.0
Jeff Garcia         2007      99          209       327         2440.0           13            4.0
Brodie Croyle       2006      10            3         7           23.0            0            2.0
Todd Collins        2007      62           67       105          888.0            5            0.0
Damon Huard         2007      76          206       332         2257.0           11           13.0
Brett Favre         2007     146          356       535         4157.0           28           15.0
Charlie Batch       2007      53           17        36          232.0            2            3.0
Gus Frerotte        2007      81           94       167         1014.0            7           12.0
Jake Delhomme       2007       6           55        86          617.0            8            1.0
Peyton Manning      2007     147          337       515         4040.0           31           14.0
Vince Young         2006     143          184       356         2199.0           12           13.0
Donovan McNabb      2007     123          291       473         3324.0           20            7.0
Brian Griese        2007      54          161       262         1803.0           10           12.0
Jay Cutler          2006      75           81       137         1001.0            9            5.0
Daunte Culpepper    2007      51          108       185         1332.0            5            5.0
Kelly Holcomb       2007      15           42        83          511.0            2            1.0
Matt Leinart        2006     121          213       376         2542.0           11           12.0
Ingle Martin        2006      17            0         0            0.0            0            0.0
Jon Kitna           2007     147          355       563         4066.0           18           21.0
Tarvaris Jackson    2006      61           47        81          475.0            2            4.0
Kellen Clemens      2006      19            0         1            0.0            0            0.0
Charlie Whitehurst  2006       8            0         0            0.0            0            0.0
Jamie Martin        2007      12            0         0            0.0            0            0.0
Bruce Gradkowski    2006     114          177       328         1661.0            9            9.0
Kerry Collins       2007      48           50        82          531.0            0            0.0
Brad Johnson        2007      30            7        11           79.0            0            0.0
Steve McNair        2007      32          133       205         1113.0            2            4.0
Matt Hasselbeck     2007     145          352       562         3966.0           28           12.0
Trent Green         2007      15           85       141          987.0            5            7.0
Brad Smith          2006     129            0         0            0.0            0            0.0
Tom Brady           2007     143          398       578         4806.0           50            8.0
Drew Brees          2007     149          443       655         4428.0           28           18.0
Kurt Warner         2007     142          282       452         3409.0           27           17.0
A.J. Feeley         2007      36           59       103          681.0            5            8.0
Tim Rattay          2007      35           15        27          164.0            3            3.0
Chris Weinke        2007      17           13        22          104.0            1            0.0
Quinn Gray          2007      87           80       144          986.0           10            5.0
Billy Volek         2007      67            3        10            6.0            0            1.0
David Carr          2007      41           73       136          635.0            3            5.0
Chris Redman        2007      85           89       149         1079.0           10            5.0
Shaun Hill          2007      45           54        80          501.0            5            2.0
Anthony Wright      2007       9            1         7           12.0            0            0.0
Sage Rosenfels      2007     105          154       240         1684.0           15           12.0
Cleo Lemon          2007      98          173       309         1773.0            6            6.0
Chad Pennington     2007      65          179       260         1766.0           10            9.0
Vinny Testaverde    2007      79           94       172          936.0            5            6.0
Marc Bulger         2007     106          221       378         2392.0           11           15.0
Tim Hasselbeck      2007      17            0         0            0.0            0            0.0
Joey Harrington     2007      83          215       348         2215.0            7            8.0
Kyle Boller         2007     103          168       275         1743.0            9           10.0
Craig Nall          2007      17            7        15           88.0            1            0.0
Brooks Bollinger    2007      44           33        50          391.0            1            1.0
Patrick Ramsey      2007      19           29        48          262.0            1            1.0
Seneca Wallace      2007      48           19        28          215.0            2            1.0

Second, we'll do an average of those variables, which will also be grouped by player and season.

In [12]:
average_QB_stats=QB_table.groupby(['player_display_name','season']).mean()
average_QB_stats

                                 week  completions   attempts  passing_yards  passing_tds  interceptions
player_display_name season
Jeff Blake          2005     9.500000     4.000000   4.500000      27.500000     0.500000       0.000000
Daunte Culpepper    2005     4.428571    19.857143  30.857143     223.428571     0.857143       1.714286
Kerry Collins       2005     8.933333    20.133333  37.733333     250.600000     1.333333       0.866667
Tony Banks          2005    17.000000    14.000000  25.000000     173.000000     1.000000       2.000000
Charlie Batch       2005    11.666667     7.666667  12.000000      82.000000     0.333333       0.333333
Jeff Garcia         2005    11.500000    17.000000  28.833333     156.166667     0.500000       1.000000
Doug Flutie         2005    13.500000     1.250000   2.500000       7.250000     0.000000       0.000000
Brett Favre         2005     9.187500    23.250000  37.937500     242.562500     1.250000       1.812500
Todd Bouman         2005    12.000000    13.600000  24.400000     144.400000     0.400000       1.400000
Brad Johnson        2005    11.909091    16.636364  26.636364     171.363636     1.090909       0.363636
Brian Griese        2005     3.500000    18.666667  29.000000     189.333333     1.166667       1.166667
Gus Frerotte        2005     9.312500    16.062500  30.875000     187.250000     1.125000       0.812500
Kelly Holcomb       2005     9.000000    15.500000  23.000000     150.900000     1.000000       0.800000
Mark Brunell        2005     9.375000    16.375000  28.375000     190.625000     1.437500       0.625000
Jay Fiedler         2005     2.000000     4.000000   6.500000      53.500000     0.500000       0.000000
Koy Detmer          2005    10.600000     6.400000  11.200000      47.600000     0.000000       0.600000
Jake Delhomme       2005     9.125000    16.375000  27.187500     213.812500     1.500000       1.000000
Aaron Brooks        2005     7.307692    18.461538  33.153846     221.692308     1.000000       1.307692
Trent Dilfer        2005     6.727273    18.090909  30.272727     211.000000     1.000000       1.090909
Trent Green         2005     9.250000    19.812500  31.687500     250.875000     1.062500       0.625000
Drew Bledsoe        2005     9.000000    18.750000  31.187500     227.437500     1.437500       1.062500
Todd Collins        2005    11.000000     0.000000   0.000000       0.000000     0.000000       0.000000
Matt Hasselbeck     2005     9.062500    18.375000  28.125000     215.937500     1.500000       0.625000
Tim Hasselbeck      2005     1.000000     0.000000   0.000000       0.000000     0.000000       0.000000
Tim Rattay          2005     2.500000    14.000000  24.250000     166.750000     1.250000       1.500000
Kordell Stewart     2005     9.000000     0.000000   0.000000       0.000000     0.000000       0.000000
Jon Kitna           2005    16.000000     5.666667   9.666667      33.000000     0.000000       0.666667
Tom Brady           2005     9.125000    20.875000  33.125000     256.875000     1.625000       0.875000
Steve McNair        2005     8.500000    20.857143  34.000000     225.785714     1.142857       0.785714
Jamie Martin        2005    11.500000    15.500000  22.125000     159.625000     0.625000       0.875000
Peyton Manning      2005     9.062500    19.062500  28.312500     234.187500     1.750000       0.625000
Chad Pennington     2005     2.000000    16.333333  27.666667     176.666667     0.666667       1.000000
Marc Bulger         2005     5.250000    24.000000  35.875000     287.125000     1.750000       1.125000
Donovan McNabb      2005     5.444444    23.444444  39.666667     278.555556     1.777778       1.000000
Anthony Wright      2005     5.250000    20.500000  33.250000     197.750000     0.750000       1.125000
Billy Volek         2005    10.800000    10.000000  17.600000      94.800000     0.800000       0.400000
Vinny Testaverde    2005     9.000000    10.000000  17.666667     129.500000     0.166667       1.000000
Kurt Warner         2005     9.000000    24.200000  37.500000     271.300000     1.100000       0.900000
Jake Plummer        2005     9.000000    17.312500  28.500000     210.375000     1.125000       0.437500
Tommy Maddox        2005     9.000000    11.333333  23.666667     135.333333     0.666667       1.333333
David Garrard       2005    14.000000    14.000000  24.000000     159.571429     0.571429       0.142857
David Carr          2005     9.375000    16.000000  26.437500     155.500000     0.875000       0.687500
Josh McCown         2005     8.444444    18.111111  30.000000     203.555556     1.000000       1.222222
Shaun Hill          2005    17.000000     0.000000   0.000000       0.000000     0.000000       0.000000
Mike McMahon        2005    12.222222    10.444444  23.000000     128.666667     0.555556       0.888889
Drew Brees          2005     8.937500    20.187500  31.250000     223.500000     1.500000       0.937500
Mike Vick           2005     9.333333    14.266667  25.800000     160.800000     1.000000       0.866667
Quinn Gray          2005    17.000000     8.000000  14.000000     100.000000     2.000000       0.000000
Chris Weinke        2005    10.333333     2.333333   4.333333      21.333333     0.333333       0.000000
Marques Tuiasosopo  2005    14.000000    14.000000  26.000000     124.000000     1.000000       2.000000
Joey Harrington     2005     9.000000    15.666667  27.500000     168.416667     1.000000       1.000000
Sage Rosenfels      2005    11.500000     8.500000  15.250000     115.500000     1.000000       0.750000
Rex Grossman        2005    15.500000    10.000000  19.500000     129.500000     0.500000       1.000000
Kyle Boller         2005    12.111111    19.000000  32.555556     199.888889     1.222222       1.333333
Jim Sorgi           2005    11.400000     8.600000  12.400000      88.800000     0.600000       0.200000
Ken Dorsey          2005    10.333333    16.000000  30.000000     160.333333     0.666667       0.666667
Seneca Wallace      2005    10.600000     2.600000   5.000000      34.600000     0.200000       0.200000
Brooks Bollinger    2005    11.636364    13.636364  24.181818     141.636364     0.636364       0.545455
Kliff Kingsbury     2005    11.000000     1.000000   2.000000      17.000000     0.000000       0.000000
Patrick Ramsey      2005     8.000000     3.750000   6.250000      69.750000     0.250000       0.250000
Carson Palmer       2005     8.937500    21.562500  31.812500     239.750000     2.000000       0.750000
Tony Romo           2005     5.000000     0.000000   0.000000       0.000000     0.000000       0.000000
Chris Simms         2005    11.909091    17.363636  28.454545     185.000000     0.909091       0.636364
Cody Pickett        2005     9.000000     4.666667  11.666667      46.666667     0.000000       0.666667
Byron Leftwich      2005     6.454545    15.909091  27.454545     193.000000     1.363636       0.454545
Drew Bledsoe        2006     4.166667    15.000000  28.166667     194.000000     1.166667       1.333333
Bradlee Van Pelt    2005    15.000000     1.000000   4.000000       3.500000     0.000000       0.000000
J.P. Losman         2005     7.777778    12.666667  25.333333     148.888889     0.888889       0.888889
Philip Rivers       2005    14.000000     6.000000  11.000000      57.500000     0.000000       0.500000
Ryan Fitzpatrick    2005    13.500000    19.000000  33.750000     194.250000     1.000000       2.000000
Matt Mauck          2005    12.000000     7.500000  13.500000      68.000000     0.000000       0.500000
Ben Roethlisberger  2005     9.416667    14.000000  22.333333     198.750000     1.416667       0.750000
John Navarre        2005    15.000000    14.000000  24.000000     174.000000     1.000000       1.000000
Kerry Collins       2006     2.000000    14.000000  30.000000     183.000000     0.333333       2.000000
Matt Schaub         2005     9.285714     4.714286   9.142857      70.714286     0.571429       0.000000
Mark Brunell        2006     6.400000    16.200000  26.100000     178.900000     0.800000       0.400000
Kyle Orton          2005     8.866667    12.666667  24.533333     124.600000     0.600000       0.866667
Charlie Batch       2006    10.142857     4.285714   7.428571      68.142857     0.714286       0.000000
Alex Smith          2005    10.333333     9.333333  18.333333      97.222222     0.111111       1.222222
Dan Orlovsky        2005     7.000000     3.500000   8.500000      31.500000     0.000000       0.000000
Aaron Rodgers       2005    12.333333     3.000000   5.333333      21.666667     0.000000       0.333333
Eli Manning         2005     9.250000    18.375000  34.875000     235.125000     1.500000       1.062500
Charlie Frye        2005    14.000000    14.000000  23.571429     143.142857     0.571429       0.857143
Aaron Brooks        2006    10.625000    13.750000  24.000000     138.125000     0.375000       1.000000
Matt Cassel         2005    10.500000     6.500000  12.000000      91.500000     1.000000       0.500000
Peyton Manning      2006     9.187500    22.625000  34.812500     274.812500     1.937500       0.562500
Trent Green         2006    12.375000    15.125000  24.750000     167.750000     0.875000       1.125000
Steve McNair        2006     9.125000    18.437500  29.250000     190.625000     1.000000       0.750000
Daunte Culpepper    2006     2.500000    20.250000  33.500000     232.250000     0.500000       0.750000
Kurt Warner         2006     7.166667    18.000000  28.000000     229.500000     1.000000       0.833333
Jake Plummer        2006     7.583333    14.583333  26.416667     166.166667     0.916667       1.083333
Jon Kitna           2006     9.062500    23.250000  37.250000     263.000000     1.312500       1.375000
Billy Volek         2006    17.000000     1.000000   2.000000       4.000000     0.000000       0.000000
Damon Huard         2006     6.900000    14.800000  24.400000     187.800000     1.100000       0.100000
Gus Frerotte        2006    12.000000     1.000000   3.000000      27.000000     0.000000       0.000000
Jeff Garcia         2006    12.750000    14.500000  23.500000     163.625000     1.250000       0.250000
Brad Johnson        2006     8.733333    18.000000  29.266667     183.333333     0.666667       1.000000
Vinny Testaverde    2006    14.333333     0.666667   1.000000       9.666667     0.333333       0.000000
Brett Favre         2006     9.187500    21.437500  38.312500     242.812500     1.125000       1.125000
Donovan McNabb      2006     5.700000    18.000000  31.600000     261.200000     1.800000       0.600000
Jamie Martin        2006    17.000000    16.000000  24.000000     208.000000     1.000000       1.000000
Anthony Wright      2006    13.000000     1.500000   1.500000      15.500000     0.000000       0.000000
Matt Hasselbeck     2006     9.166667    17.500000  30.916667     203.500000     1.500000       1.250000
Jake Delhomme       2006     7.615385    20.230769  33.153846     215.769231     1.307692       0.846154
Brian Griese        2006     9.600000     3.600000   6.400000      44.000000     0.200000       0.400000
Cleo Lemon          2006    15.000000     9.500000  17.000000     103.000000     0.500000       0.250000
Marc Bulger         2006     9.125000    23.125000  36.750000     268.812500     1.500000       0.500000
Tim Rattay          2006    15.500000    15.250000  25.250000     187.000000     1.000000       0.500000
A.J. Feeley         2006    14.500000    13.000000  19.000000     171.000000     1.500000       0.000000
David Carr          2006     9.250000    18.875000  27.625000     172.812500     0.687500       0.750000
Sage Rosenfels      2006     8.000000     9.000000  13.000000      88.333333     1.000000       0.333333
Tom Brady           2006     9.187500    20.000000  32.312500     220.812500     1.500000       0.750000
Joey Harrington     2006    10.727273    20.272727  35.272727     203.272727     1.090909       1.363636
Marques Tuiasosopo  2006     6.000000     3.000000   6.500000      34.000000     0.500000       1.000000
Drew Brees          2006     9.125000    22.312500  34.687500     276.500000     1.625000       0.687500
Chris Weinke        2006    15.000000    18.666667  32.000000     208.333333     0.666667       1.333333
Chad Pennington     2006     9.000000    19.562500  30.312500     209.500000     1.062500       1.000000
Mike Vick           2006     9.250000    12.812500  24.312500     154.625000     1.250000       0.812500
Quinn Gray          2006    17.000000    13.000000  22.000000     166.000000     0.000000       0.000000
Seneca Wallace      2006     8.166667    13.666667  23.500000     154.500000     1.333333       1.166667
Jared Lorenzen      2006    17.000000     0.000000   0.000000       0.000000     0.000000       0.000000
Ken Dorsey          2006    16.000000     0.000000   1.000000       0.000000     0.000000       0.000000
Chris Simms         2006     2.000000    19.333333  35.333333     195.000000     0.333333       2.333333
Rex Grossman        2006     9.125000    16.375000  30.000000     199.812500     1.437500       1.250000
Patrick Ramsey      2006    12.000000     0.000000   1.000000       0.000000     0.000000       0.000000
Brooks Bollinger    2006    10.500000     6.500000   9.000000      73.000000     0.000000       0.500000
Byron Leftwich      2006     3.666667    18.166667  30.666667     193.000000     1.166667       0.833333
Carson Palmer       2006     9.250000    20.250000  32.500000     252.250000     1.750000       0.812500
Tony Romo           2006    10.923077    16.923077  25.923077     223.307692     1.461538       1.000000
Josh McCown         2006    13.000000     0.000000   0.000000       0.000000     0.000000       0.000000
Kyle Boller         2006     8.500000     8.250000  13.750000     121.250000     1.250000       0.500000
David Garrard       2006    12.500000    14.500000  24.100000     173.500000     1.000000       0.900000
Jason Campbell      2006    14.000000    15.714286  29.571429     185.285714     1.428571       0.857143
Matt Schaub         2006    12.000000     3.600000   5.400000      41.600000     0.200000       0.400000
Philip Rivers       2006     9.375000    17.750000  28.750000     211.687500     1.375000       0.562500
J.P. Losman         2006     9.062500    16.812500  26.875000     190.625000     1.187500       0.875000
Aaron Rodgers       2006     7.500000     3.000000   7.500000      23.000000     0.000000       0.000000
Brett Basanez       2006    15.000000     6.000000  11.000000      56.000000     0.000000       1.000000
Derek Anderson      2006    14.500000    16.500000  29.250000     198.250000     1.250000       2.000000
Ryan Fitzpatrick    2006    17.000000     0.000000   0.000000       0.000000     0.000000       0.000000
Eli Manning         2006     9.312500    18.812500  32.625000     202.750000     1.562500       1.125000
Ben Roethlisberger  2006     9.866667    18.733333  31.333333     235.200000     1.200000       1.533333
Charlie Frye        2006     7.846154    19.307692  30.076923     188.384615     0.769231       1.307692
Matt Cassel         2006    13.000000     1.000000   1.600000       6.400000     0.000000       0.000000
Alex Smith          2006     9.125000    16.187500  27.687500     181.312500     1.000000       0.937500
Andrew Walter       2006     7.833333    12.250000  23.000000     139.750000     0.250000       1.083333
Trent Dilfer        2007     9.428571    16.142857  31.285714     166.571429     1.000000       1.714286
Jeff Garcia         2007     7.615385    16.076923  25.153846     187.692308     1.000000       0.307692
Brodie Croyle       2006     5.000000     1.500000   3.500000      11.500000     0.000000       1.000000
Todd Collins        2007    15.500000    16.750000  26.250000     222.000000     1.250000       0.000000
Damon Huard         2007     6.909091    18.727273  30.181818     205.181818     1.000000       1.181818
Brett Favre         2007     9.125000    22.250000  33.437500     259.812500     1.750000       0.937500
Charlie Batch       2007     7.571429     2.428571   5.142857      33.142857     0.285714       0.428571
Gus Frerotte        2007    10.125000    11.750000  20.875000     126.750000     0.875000       1.500000
Jake Delhomme       2007     2.000000    18.333333  28.666667     205.666667     2.666667       0.333333
Peyton Manning      2007     9.187500    21.062500  32.187500     252.500000     1.937500       0.875000
Vince Young         2006     9.533333    12.266667  23.733333     146.600000     0.800000       0.866667
Donovan McNabb      2007     8.785714    20.785714  33.785714     237.428571     1.428571       0.500000
Brian Griese        2007     7.714286    23.000000  37.428571     257.571429     1.428571       1.714286
Jay Cutler          2006    15.000000    16.200000  27.400000     200.200000     1.800000       1.000000
Daunte Culpepper    2007     7.285714    15.428571  26.428571     190.285714     0.714286       0.714286
Kelly Holcomb       2007     5.000000    14.000000  27.666667     170.333333     0.666667       0.333333
Matt Leinart        2006    10.083333    17.750000  31.333333     211.833333     0.916667       1.000000
Ingle Martin        2006    17.000000     0.000000   0.000000       0.000000     0.000000       0.000000
Jon Kitna           2007     9.187500    22.187500  35.187500     254.125000     1.125000       1.312500
Tarvaris Jackson    2006    15.250000    11.750000  20.250000     118.750000     0.500000       1.000000
Kellen Clemens      2006     9.500000     0.000000   0.500000       0.000000     0.000000       0.000000
Charlie Whitehurst  2006     4.000000     0.000000   0.000000       0.000000     0.000000       0.000000
Jamie Martin        2007    12.000000     0.000000   0.000000       0.000000     0.000000       0.000000
Bruce Gradkowski    2006     8.769231    13.615385  25.230769     127.769231     0.692308       0.692308
Kerry Collins       2007     8.000000     8.333333  13.666667      88.500000     0.000000       0.000000
Brad Johnson        2007    10.000000     2.333333   3.666667      26.333333     0.000000       0.000000
Steve McNair        2007     5.333333    22.166667  34.166667     185.500000     0.333333       0.666667
Matt Hasselbeck     2007     9.062500    22.000000  35.125000     247.875000     1.750000       0.750000
Trent Green         2007     3.000000    17.000000  28.200000     197.400000     1.000000       1.400000
Brad Smith          2006     9.923077     0.000000   0.000000       0.000000     0.000000       0.000000
Tom Brady           2007     8.937500    24.875000  36.125000     300.375000     3.125000       0.500000
Drew Brees          2007     9.312500    27.687500  40.937500     276.750000     1.750000       1.125000
Kurt Warner         2007    10.142857    20.142857  32.285714     243.500000     1.928571       1.214286
A.J. Feeley         2007    12.000000    19.666667  34.333333     227.000000     1.666667       2.666667
Tim Rattay          2007     8.750000     3.750000   6.750000      41.000000     0.750000       0.750000
Chris Weinke        2007    17.000000    13.000000  22.000000     104.000000     1.000000       0.000000
Quinn Gray          2007    10.875000    10.000000  18.000000     123.250000     1.250000       0.625000
Billy Volek         2007    13.400000     0.600000   2.000000       1.200000     0.000000       0.200000
David Carr          2007     6.833333    12.166667  22.666667     105.833333     0.500000       0.833333
Chris Redman        2007    14.166667    14.833333  24.833333     179.833333     1.666667       0.833333
Shaun Hill          2007    15.000000    18.000000  26.666667     167.000000     1.666667       0.666667
Anthony Wright      2007     4.500000     0.500000   3.500000       6.000000     0.000000       0.000000
Sage Rosenfels      2007    11.666667    17.111111  26.666667     187.111111     1.666667       1.333333

We can also create some new variables pertaining to the completion percentage as well as the ratio between touchdowns and interceptions.

In [14]:
sum_QB_stats['completion_percentage']=QB_table.groupby(['player_display_name','season']).completions.sum()/QB_table.groupby(['player_display_name','season']).attempts.sum()
sum_QB_stats['td_int_ratio']=QB_table.groupby(['player_display_name','season']).passing_tds.sum()/QB_table.groupby(['player_display_name','season']).interceptions.sum()

Our final table below contains the grouped sums along with the newly defined variables.

In [15]:
sum_QB_stats

                            week  completions  attempts  passing_yards  passing_tds  interceptions  completion_percentage  td_int_ratio
player_display_name season
Jeff Blake          2005      19            8         9           55.0            1            0.0               0.888889           inf
Daunte Culpepper    2005      31          139       216         1564.0            6           12.0               0.643519      0.500000
Kerry Collins       2005     134          302       566         3759.0           20           13.0               0.533569      1.538462
Tony Banks          2005      17           14        25          173.0            1            2.0               0.560000      0.500000
Charlie Batch       2005      35           23        36          246.0            1            1.0               0.638889      1.000000
Jeff Garcia         2005      69          102       173          937.0            3            6.0               0.589595      0.500000
Doug Flutie         2005      54            5        10           29.0            0            0.0               0.500000           NaN
Brett Favre         2005     147          372       607         3881.0           20           29.0               0.612850      0.689655
Todd Bouman         2005      60           68       122          722.0            2            7.0               0.557377      0.285714
Brad Johnson        2005     131          183       293         1885.0           12            4.0               0.624573      3.000000
Brian Griese        2005      21          112       174         1136.0            7            7.0               0.643678      1.000000
Gus Frerotte        2005     149          257       494         2996.0           18           13.0               0.520243      1.384615
Kelly Holcomb       2005      90          155       230         1509.0           10            8.0               0.673913      1.250000
Mark Brunell        2005     150          262       454         3050.0           23           10.0               0.577093      2.300000
Jay Fiedler         2005       4            8        13          107.0            1            0.0               0.615385           inf
Koy Detmer          2005      53           32        56          238.0            0            3.0               0.571429      0.000000
Jake Delhomme       2005     146          262       435         3421.0           24           16.0               0.602299      1.500000
Aaron Brooks        2005      95          240       431         2882.0           13           17.0               0.556845      0.764706
Trent Dilfer        2005      74          199       333         2321.0           11           12.0               0.597598      0.916667
Trent Green         2005     148          317       507         4014.0           17           10.0               0.625247      1.700000
Drew Bledsoe        2005     144          300       499         3639.0           23           17.0               0.601202      1.352941
Todd Collins        2005      11            0         0            0.0            0            0.0                    NaN           NaN
Matt Hasselbeck     2005     145          294       450         3455.0           24           10.0               0.653333      2.400000
Tim Hasselbeck      2005       1            0         0            0.0            0            0.0                    NaN           NaN
Tim Rattay          2005      10           56        97          667.0            5            6.0               0.577320      0.833333
Kordell Stewart     2005       9            0         0            0.0            0            0.0                    NaN           NaN
Jon Kitna           2005      48           17        29           99.0            0            2.0               0.586207      0.000000
Tom Brady           2005     146          334       530         4110.0           26           14.0               0.630189      1.857143
Steve McNair        2005     119          292       476         3161.0           16           11.0               0.613445      1.454545
Jamie Martin        2005      92          124       177         1277.0            5            7.0               0.700565      0.714286
Peyton Manning      2005     145          305       453         3747.0           28           10.0               0.673289      2.800000
Chad Pennington     2005       6           49        83          530.0            2            3.0               0.590361      0.666667
Marc Bulger         2005      42          192       287         2297.0           14            9.0               0.668990      1.555556
Donovan McNabb      2005      49          211       357         2507.0           16            9.0               0.591036      1.777778
Anthony Wright      2005      42          164       266         1582.0            6            9.0               0.616541      0.666667
Billy Volek         2005      54           50        88          474.0            4            2.0               0.568182      2.000000
Vinny Testaverde    2005      54           60       106          777.0            1            6.0               0.566038      0.166667
Kurt Warner         2005      90          242       375         2713.0           11            9.0               0.645333      1.222222
Jake Plummer        2005     144          277       456         3366.0           18            7.0               0.607456      2.571429
Tommy Maddox        2005      27           34        71          406.0            2            4.0               0.478873      0.500000
David Garrard       2005      98           98       168         1117.0            4            1.0               0.583333      4.000000
David Carr          2005     150          256       423         2488.0           14           11.0               0.605201      1.272727
Josh McCown         2005      76          163       270         1832.0            9           11.0               0.603704      0.818182
Shaun Hill          2005      17            0         0            0.0            0            0.0                    NaN           NaN
Mike McMahon        2005     110           94       207         1158.0            5            8.0               0.454106      0.625000
Drew Brees          2005     143          323       500         3576.0           24           15.0               0.646000      1.600000
Mike Vick           2005     140          214       387         2412.0           15           13.0               0.552972      1.153846
Quinn Gray          2005      17            8        14          100.0            2            0.0               0.571429           inf
Chris Weinke        2005      31            7        13           64.0            1            0.0               0.538462           inf
Marques Tuiasosopo  2005      14           14        26          124.0            1            2.0               0.538462      0.500000
Joey Harrington     2005     108          188       330         2021.0           12           12.0               0.569697      1.000000
Sage Rosenfels      2005      46           34        61          462.0            4            3.0               0.557377      1.333333
Rex Grossman        2005      31           20        39          259.0            1            2.0               0.512821      0.500000
Kyle Boller         2005     109          171       293         1799.0           11           12.0               0.583618      0.916667
Jim Sorgi           2005      57           43        62          444.0            3            1.0               0.693548      3.000000
Ken Dorsey          2005      31           48        90          481.0            2            2.0               0.533333      1.000000
Seneca Wallace      2005      53           13        25          173.0            1            1.0               0.520000      1.000000
Brooks Bollinger    2005     128          150       266         1558.0            7            6.0               0.563910      1.166667
Kliff Kingsbury     2005      11            1         2           17.0            0            0.0               0.500000           NaN
Patrick Ramsey      2005      32           15        25          279.0            1            1.0               0.600000      1.000000
Carson Palmer       2005     143          345       509         3836.0           32           12.0               0.677800      2.666667
Tony Romo           2005       5            0         0            0.0            0            0.0                    NaN           NaN
Chris Simms         2005     131          191       313         2035.0           10            7.0               0.610224      1.428571
Cody Pickett        2005      27           14        35          140.0            0            2.0               0.400000      0.000000
Byron Leftwich      2005      71          175       302         2123.0           15            5.0               0.579470      3.000000
Drew Bledsoe        2006      25           90       169         1164.0            7            8.0               0.532544      0.875000
Bradlee Van Pelt    2005      30            2         8            7.0            0            0.0               0.250000           NaN
J.P. Losman         2005      70          114       228         1340.0            8            8.0               0.500000      1.000000
Philip Rivers       2005      28           12        22          115.0            0            1.0               0.545455      0.000000
Ryan Fitzpatrick    2005      54           76       135          777.0            4            8.0               0.562963      0.500000
Matt Mauck          2005      24           15        27          136.0            0            1.0               0.555556      0.000000
Ben Roethlisberger  2005     113          168       268         2385.0           17            9.0               0.626866      1.888889
John Navarre        2005      15           14        24          174.0            1            1.0               0.583333      1.000000
Kerry Collins       2006       6           42        90          549.0            1            6.0               0.466667      0.166667
Matt Schaub         2005      65           33        64          495.0            4            0.0               0.515625           inf
Mark Brunell        2006      64          162       261         1789.0            8            4.0               0.620690      2.000000
Kyle Orton          2005     133          190       368         1869.0            9           13.0               0.516304      0.692308
Charlie Batch       2006      71           30        52          477.0            5            0.0               0.576923           inf
Alex Smith          2005      93           84       165          875.0            1           11.0               0.509091      0.090909
Dan Orlovsky        2005      14            7        17           63.0            0            0.0               0.411765           NaN
Aaron Rodgers       2005      37            9        16           65.0            0            1.0               0.562500      0.000000
Eli Manning         2005     148          294       558         3762.0           24           17.0               0.526882      1.411765
Charlie Frye        2005      98           98       165         1002.0            4            6.0               0.593939      0.666667
Aaron Brooks        2006      85          110       192         1105.0            3            8.0               0.572917      0.375000
Matt Cassel         2005      21           13        24          183.0            2            1.0               0.541667      2.000000
Peyton Manning      2006     147          362       557         4397.0           31            9.0               0.649910      3.444444
Trent Green         2006      99          121       198         1342.0            7            9.0               0.611111      0.777778
Steve McNair        2006     146          295       468         3050.0           16           12.0               0.630342      1.333333
Daunte Culpepper    2006      10           81       134          929.0            2            3.0               0.604478      0.666667
Kurt Warner         2006      43          108       168         1377.0            6            5.0               0.642857      1.200000
Jake Plummer        2006      91          175       317         1994.0           11           13.0               0.552050      0.846154
Jon Kitna           2006     145          372       596         4208.0           21           22.0               0.624161      0.954545
Billy Volek         2006      17            1         2            4.0            0            0.0               0.500000           NaN
Damon Huard         2006      69          148       244         1878.0           11            1.0               0.606557     11.000000
Gus Frerotte        2006      12            1         3           27.0            0            0.0               0.333333           NaN
Jeff Garcia         2006     102          116       188         1309.0           10            2.0               0.617021      5.000000
Brad Johnson        2006     131          270       439         2750.0           10           15.0               0.615034      0.666667
Vinny Testaverde    2006      43            2         3           29.0            1            0.0               0.666667           inf
Brett Favre         2006     147          343       613         3885.0           18           18.0               0.559543      1.000000
Donovan McNabb      2006      57          180       316         2612.0           18            6.0               0.569620      3.000000
Jamie Martin        2006      17           16        24          208.0            1            1.0               0.666667      1.000000
Anthony Wright      2006      26            3         3           31.0            0            0.0               1.000000           NaN
Matt Hasselbeck     2006     110          210       371         2442.0           18           15.0               0.566038      1.200000
Jake Delhomme       2006      99          263       431         2805.0           17           11.0               0.610209      1.545455
Brian Griese        2006      48           18        32          220.0            1            2.0               0.562500      0.500000
Cleo Lemon          2006      60           38        68          412.0            2            1.0               0.558824      2.000000
Marc Bulger         2006     146          370       588         4301.0           24            8.0               0.629252      3.000000
Tim Rattay          2006      62           61       101          748.0            4            2.0               0.603960      2.000000
A.J. Feeley         2006      29           26        38          342.0            3            0.0               0.684211           inf
David Carr          2006     148          302       442         2765.0           11           12.0               0.683258      0.916667
Sage Rosenfels      2006      24           27        39          265.0            3            1.0               0.692308      3.000000
Tom Brady           2006     147          320       517         3533.0           24           12.0               0.618956      2.000000
Joey Harrington     2006     118          223       388         2236.0           12           15.0               0.574742      0.800000
Marques Tuiasosopo  2006      12            6        13           68.0            1            2.0               0.461538      0.500000
Drew Brees          2006     146          357       555         4424.0           26           11.0               0.643243      2.363636
Chris Weinke        2006      45           56        96          625.0            2            4.0               0.583333      0.500000
Chad Pennington     2006     144          313       485         3352.0           17           16.0               0.645361      1.062500
Mike Vick           2006     148          205       389         2474.0           20           13.0               0.526992      1.538462
Quinn Gray          2006      17           13        22          166.0            0            0.0               0.590909           NaN
Seneca Wallace      2006      49           82       141          927.0            8            7.0               0.581560      1.142857
Jared Lorenzen      2006      17            0         0            0.0            0            0.0                    NaN           NaN
Ken Dorsey          2006      16            0         1            0.0            0            0.0               0.000000           NaN
Chris Simms         2006       6           58       106          585.0            1            7.0               0.547170      0.142857
Rex Grossman        2006     146          262       480         3197.0           23           20.0               0.545833      1.150000
Patrick Ramsey      2006      12            0         1            0.0            0            0.0               0.000000           NaN
Brooks Bollinger    2006      21           13        18          146.0            0            1.0               0.722222      0.000000
Byron Leftwich      2006      22          109       184         1158.0            7            5.0               0.592391      1.400000
Carson Palmer       2006     148          324       520         4036.0           28           13.0               0.623077      2.153846
Tony Romo           2006     142          220       337         2903.0           19           13.0               0.652819      1.461538
Josh McCown         2006      13            0         0            0.0            0            0.0                    NaN           NaN
Kyle Boller         2006      34           33        55          485.0            5            2.0               0.600000      2.500000
David Garrard       2006     125          145       241         1735.0           10            9.0               0.601660      1.111111
Jason Campbell      2006      98          110       207         1297.0           10            6.0               0.531401      1.666667
Matt Schaub         2006      60           18        27          208.0            1            2.0               0.666667      0.500000
Philip Rivers       2006     150          284       460         3387.0           22            9.0               0.617391      2.444444
J.P. Losman         2006     145          269       430         3050.0           19           14.0               0.625581      1.357143
Aaron Rodgers       2006      15            6        15           46.0            0            0.0               0.400000           NaN
Brett Basanez       2006      15            6        11           56.0            0            1.0               0.545455      0.000000
Derek Anderson      2006      58           66       117          793.0            5            8.0               0.564103      0.625000
Ryan Fitzpatrick    2006      17            0         0            0.0            0            0.0                    NaN           NaN
Eli Manning         2006     149          301       522         3244.0           25           18.0               0.576628      1.388889
Ben Roethlisberger  2006     148          281       470         3528.0           18           23.0               0.597872      0.782609
Charlie Frye        2006     102          251       391         2449.0           10           17.0               0.641944      0.588235
Matt Cassel         2006      65            5         8           32.0            0            0.0               0.625000           NaN
Alex Smith          2006     146          259       443         2901.0           16           15.0               0.584650      1.066667

Something will go here.

In [18]:
sum_QB_stats.loc[sum_QB_stats.attempts >= 50]

                                 week  completions  attempts  passing_yards  passing_tds  interceptions  completion_percentage  td_int_ratio
player_display_name      season
Daunte Culpepper         2005      31          139       216         1564.0            6           12.0               0.643519      0.500000
Kerry Collins            2005     134          302       566         3759.0           20           13.0               0.533569      1.538462
Jeff Garcia              2005      69          102       173          937.0            3            6.0               0.589595      0.500000
Brett Favre              2005     147          372       607         3881.0           20           29.0               0.612850      0.689655
Todd Bouman              2005      60           68       122          722.0            2            7.0               0.557377      0.285714
Brad Johnson             2005     131          183       293         1885.0           12            4.0               0.624573      3.000000
Brian Griese             2005      21          112       174         1136.0            7            7.0               0.643678      1.000000
Gus Frerotte             2005     149          257       494         2996.0           18           13.0               0.520243      1.384615
Kelly Holcomb            2005      90          155       230         1509.0           10            8.0               0.673913      1.250000
Mark Brunell             2005     150          262       454         3050.0           23           10.0               0.577093      2.300000
Koy Detmer               2005      53           32        56          238.0            0            3.0               0.571429      0.000000
Jake Delhomme            2005     146          262       435         3421.0           24           16.0               0.602299      1.500000
Aaron Brooks             2005      95          240       431         2882.0           13           17.0               0.556845      0.764706
Trent Dilfer             2005      74          199       333         2321.0           11           12.0               0.597598      0.916667
Trent Green              2005     148          317       507         4014.0           17           10.0               0.625247      1.700000
Drew Bledsoe             2005     144          300       499         3639.0           23           17.0               0.601202      1.352941
Matt Hasselbeck          2005     145          294       450         3455.0           24           10.0               0.653333      2.400000
Tim Rattay               2005      10           56        97          667.0            5            6.0               0.577320      0.833333
Tom Brady                2005     146          334       530         4110.0           26           14.0               0.630189      1.857143
Steve McNair             2005     119          292       476         3161.0           16           11.0               0.613445      1.454545
Jamie Martin             2005      92          124       177         1277.0            5            7.0               0.700565      0.714286
Peyton Manning           2005     145          305       453         3747.0           28           10.0               0.673289      2.800000
Chad Pennington          2005       6           49        83          530.0            2            3.0               0.590361      0.666667
Marc Bulger              2005      42          192       287         2297.0           14            9.0               0.668990      1.555556
Donovan McNabb           2005      49          211       357         2507.0           16            9.0               0.591036      1.777778
Anthony Wright           2005      42          164       266         1582.0            6            9.0               0.616541      0.666667
Billy Volek              2005      54           50        88          474.0            4            2.0               0.568182      2.000000
Vinny Testaverde         2005      54           60       106          777.0            1            6.0               0.566038      0.166667
Kurt Warner              2005      90          242       375         2713.0           11            9.0               0.645333      1.222222
Jake Plummer             2005     144          277       456         3366.0           18            7.0               0.607456      2.571429
Tommy Maddox             2005      27           34        71          406.0            2            4.0               0.478873      0.500000
David Garrard            2005      98           98       168         1117.0            4            1.0               0.583333      4.000000
David Carr               2005     150          256       423         2488.0           14           11.0               0.605201      1.272727
Josh McCown              2005      76          163       270         1832.0            9           11.0               0.603704      0.818182
Mike McMahon             2005     110           94       207         1158.0            5            8.0               0.454106      0.625000
Drew Brees               2005     143          323       500         3576.0           24           15.0               0.646000      1.600000
Mike Vick                2005     140          214       387         2412.0           15           13.0               0.552972      1.153846
Joey Harrington          2005     108          188       330         2021.0           12           12.0               0.569697      1.000000
Sage Rosenfels           2005      46           34        61          462.0            4            3.0               0.557377      1.333333
Kyle Boller              2005     109          171       293         1799.0           11           12.0               0.583618      0.916667
Jim Sorgi                2005      57           43        62          444.0            3            1.0               0.693548      3.000000
Ken Dorsey               2005      31           48        90          481.0            2            2.0               0.533333      1.000000
Brooks Bollinger         2005     128          150       266         1558.0            7            6.0               0.563910      1.166667
Carson Palmer            2005     143          345       509         3836.0           32           12.0               0.677800      2.666667
Chris Simms              2005     131          191       313         2035.0           10            7.0               0.610224      1.428571
Byron Leftwich           2005      71          175       302         2123.0           15            5.0               0.579470      3.000000
Drew Bledsoe             2006      25           90       169         1164.0            7            8.0               0.532544      0.875000
J.P. Losman              2005      70          114       228         1340.0            8            8.0               0.500000      1.000000
Ryan Fitzpatrick         2005      54           76       135          777.0            4            8.0               0.562963      0.500000
Ben Roethlisberger       2005     113          168       268         2385.0           17            9.0               0.626866      1.888889
Kerry Collins            2006       6           42        90          549.0            1            6.0               0.466667      0.166667
Matt Schaub              2005      65           33        64          495.0            4            0.0               0.515625           inf
Mark Brunell             2006      64          162       261         1789.0            8            4.0               0.620690      2.000000
Kyle Orton               2005     133          190       368         1869.0            9           13.0               0.516304      0.692308
Charlie Batch            2006      71           30        52          477.0            5            0.0               0.576923           inf
Alex Smith               2005      93           84       165          875.0            1           11.0               0.509091      0.090909
Eli Manning              2005     148          294       558         3762.0           24           17.0               0.526882      1.411765
Charlie Frye             2005      98           98       165         1002.0            4            6.0               0.593939      0.666667
Aaron Brooks             2006      85          110       192         1105.0            3            8.0               0.572917      0.375000
Peyton Manning           2006     147          362       557         4397.0           31            9.0               0.649910      3.444444
Trent Green              2006      99          121       198         1342.0            7            9.0               0.611111      0.777778
Steve McNair             2006     146          295       468         3050.0           16           12.0               0.630342      1.333333
Daunte Culpepper         2006      10           81       134          929.0            2            3.0               0.604478      0.666667
Kurt Warner              2006      43          108       168         1377.0            6            5.0               0.642857      1.200000
Jake Plummer             2006      91          175       317         1994.0           11           13.0               0.552050      0.846154
Jon Kitna                2006     145          372       596         4208.0           21           22.0               0.624161      0.954545
Damon Huard              2006      69          148       244         1878.0           11            1.0               0.606557     11.000000
Jeff Garcia              2006     102          116       188         1309.0           10            2.0               0.617021      5.000000
Brad Johnson             2006     131          270       439         2750.0           10           15.0               0.615034      0.666667
Brett Favre              2006     147          343       613         3885.0           18           18.0               0.559543      1.000000
Donovan McNabb           2006      57          180       316         2612.0           18            6.0               0.569620      3.000000
Matt Hasselbeck          2006     110          210       371         2442.0           18           15.0               0.566038      1.200000
Jake Delhomme            2006      99          263       431         2805.0           17           11.0               0.610209      1.545455
Cleo Lemon               2006      60           38        68          412.0            2            1.0               0.558824      2.000000
Marc Bulger              2006     146          370       588         4301.0           24            8.0               0.629252      3.000000
Tim Rattay               2006      62           61       101          748.0            4            2.0               0.603960      2.000000
David Carr               2006     148          302       442         2765.0           11           12.0               0.683258      0.916667
Tom Brady                2006     147          320       517         3533.0           24           12.0               0.618956      2.000000
Joey Harrington          2006     118          223       388         2236.0           12           15.0               0.574742      0.800000
Drew Brees               2006     146          357       555         4424.0           26           11.0               0.643243      2.363636
Chris Weinke             2006      45           56        96          625.0            2            4.0               0.583333      0.500000
Chad Pennington          2006     144          313       485         3352.0           17           16.0               0.645361      1.062500
Mike Vick                2006     148          205       389         2474.0           20           13.0               0.526992      1.538462
Seneca Wallace           2006      49           82       141          927.0            8            7.0               0.581560      1.142857
Chris Simms              2006       6           58       106          585.0            1            7.0               0.547170      0.142857
Rex Grossman             2006     146          262       480         3197.0           23           20.0               0.545833      1.150000
Byron Leftwich           2006      22          109       184         1158.0            7            5.0               0.592391      1.400000
Carson Palmer            2006     148          324       520         4036.0           28           13.0               0.623077      2.153846
Tony Romo                2006     142          220       337         2903.0           19           13.0               0.652819      1.461538
Kyle Boller              2006      34           33        55          485.0            5            2.0               0.600000      2.500000
David Garrard            2006     125          145       241         1735.0           10            9.0               0.601660      1.111111
Jason Campbell           2006      98          110       207         1297.0           10            6.0               0.531401      1.666667
Philip Rivers            2006     150          284       460         3387.0           22            9.0               0.617391      2.444444
J.P. Losman              2006     145          269       430         3050.0           19           14.0               0.625581      1.357143
Derek Anderson           2006      58           66       117          793.0            5            8.0               0.564103      0.625000
Eli Manning              2006     149          301       522         3244.0           25           18.0               0.576628      1.388889
Ben Roethlisberger       2006     148          281       470         3528.0           18           23.0               0.597872      0.782609
Charlie Frye             2006     102          251       391         2449.0           10           17.0               0.641944      0.588235
Alex Smith               2006     146          259       443         2901.0           16           15.0               0.584650      1.066667
Andrew Walter            2006      94          147       276         1677.0            3           13.0               0.532609      0.230769
Trent Dilfer             2007      66          113       219         1166.0            7           12.0               0.515982      0.583333
Jeff Garcia              2007      99          209       327         2440.0           13            4.0               0.639144      3.250000
Todd Collins             2007      62           67       105          888.0            5            0.0               0.638095           inf
Damon Huard              2007      76          206       332         2257.0           11           13.0               0.620482      0.846154
Brett Favre              2007     146          356       535         4157.0           28           15.0               0.665421      1.866667
Gus Frerotte             2007      81           94       167         1014.0            7           12.0               0.562874      0.583333
Jake Delhomme            2007       6           55        86          617.0            8            1.0               0.639535      8.000000
Peyton Manning           2007     147          337       515         4040.0           31           14.0               0.654369      2.214286
Vince Young              2006     143          184       356         2199.0           12           13.0               0.516854      0.923077
Donovan McNabb           2007     123          291       473         3324.0           20            7.0               0.615222      2.857143
Brian Griese             2007      54          161       262         1803.0           10           12.0               0.614504      0.833333
Jay Cutler               2006      75           81       137         1001.0            9            5.0               0.591241      1.800000
Daunte Culpepper         2007      51          108       185         1332.0            5            5.0               0.583784      1.000000
Kelly Holcomb            2007      15           42        83          511.0            2            1.0               0.506024      2.000000
Matt Leinart             2006     121          213       376         2542.0           11           12.0               0.566489      0.916667
Jon Kitna                2007     147          355       563         4066.0           18           21.0               0.630551      0.857143
Tarvaris Jackson         2006      61           47        81          475.0            2            4.0               0.580247      0.500000
Bruce Gradkowski         2006     114          177       328         1661.0            9            9.0               0.539634      1.000000
Kerry Collins            2007      48           50        82          531.0            0            0.0               0.609756           NaN
Steve McNair             2007      32          133       205         1113.0            2            4.0               0.648780      0.500000
Matt Hasselbeck          2007     145          352       562         3966.0           28           12.0               0.626335      2.333333
Trent Green              2007      15           85       141          987.0            5            7.0               0.602837      0.714286
Tom Brady                2007     143          398       578         4806.0           50            8.0               0.688581      6.250000
Drew Brees               2007     149          443       655         4428.0           28           18.0               0.676336      1.555556
Kurt Warner              2007     142          282       452         3409.0           27           17.0               0.623894      1.588235
A.J. Feeley              2007      36           59       103          681.0            5            8.0               0.572816      0.625000
Quinn Gray               2007      87           80       144          986.0           10            5.0               0.555556      2.000000
David Carr               2007      41           73       136          635.0            3            5.0               0.536765      0.600000
Chris Redman             2007      85           89       149         1079.0           10            5.0               0.597315      2.000000
Shaun Hill               2007      45           54        80          501.0            5            2.0               0.675000      2.500000
Sage Rosenfels           2007     105          154       240         1684.0           15           12.0               0.641667      1.250000
Cleo Lemon               2007      98          173       309         1773.0            6            6.0               0.559871      1.000000
Chad Pennington          2007      65          179       260         1766.0           10            9.0               0.688462      1.111111
Vinny Testaverde         2007      79           94       172          936.0            5            6.0               0.546512      0.833333
Marc Bulger              2007     106          221       378         2392.0           11           15.0               0.584656      0.733333
Joey Harrington          2007      83          215       348         2215.0            7            8.0               0.617816      0.875000
Kyle Boller              2007     103          168       275         1743.0            9           10.0               0.610909      0.900000
Brooks Bollinger         2007      44           33        50          391.0            1            1.0               0.660000      1.000000
Josh McCown              2007      83          111       191         1151.0           10           11.0               0.581152      0.909091
Byron Leftwich           2007      23           32        59          279.0            1            3.0               0.542373      0.333333

Another thing will go here.

In [26]:
sum_QB_stats_percent_sort=sum_QB_stats.sort_values(by="completion_percentage",ascending=False)
sum_QB_stats_percent_sort[:40]

                            week  completions  attempts  passing_yards  passing_tds  interceptions  completion_percentage  td_int_ratio
player_display_name season
Anthony Wright      2006      26            3         3           31.0            0            0.0               1.000000           NaN
Matt Gutierrez      2007      18            1         1           15.0            0            0.0               1.000000           NaN
Dennis Dixon        2008      17            1         1            3.0            0            0.0               1.000000           NaN
Matt Gutierrez      2009       7            1         1            3.0            0            0.0               1.000000           NaN
Brad Smith          2009     101            1         1           27.0            0            0.0               1.000000           NaN
Billy Volek         2010      21            1         1            8.0            0            0.0               1.000000           NaN
Jordan Palmer       2010      11            3         3           18.0            0            0.0               1.000000           NaN
Brian Hoyer         2011      29            1         1           22.0            0            0.0               1.000000           NaN
Tyrod Taylor        2011      28            1         1           18.0            0            0.0               1.000000           NaN
Derek Anderson      2012      20            4         4           58.0            0            0.0               1.000000           NaN
Trent Edwards       2012      17            2         2           14.0            0            0.0               1.000000           NaN
Chase Daniel        2012      11            1         1           10.0            0            0.0               1.000000           NaN
Colt McCoy          2013      28            1         1           13.0            0            0.0               1.000000           NaN
Tarvaris Jackson    2014      16            1         1            0.0            0            0.0               1.000000           NaN
Matt Moore          2015       7            1         1           14.0            0            0.0               1.000000           NaN
Chase Daniel        2015      23            2         2            4.0            0            0.0               1.000000           NaN
Scott Tolzien       2015      30            1         1            4.0            0            0.0               1.000000           NaN
Ryan Nassib         2015      16            5         5           68.0            1            0.0               1.000000           inf
Chase Daniel        2016      16            1         1           16.0            0            0.0               1.000000           NaN
Taylor Heinicke     2017      16            1         1           10.0            0            0.0               1.000000           NaN
Alex Tanney         2019      15            1         1            1.0            0            0.0               1.000000           NaN
AJ McCarron         2020      31            1         1           20.0            0            0.0               1.000000           NaN
Easton Stick        2020       7            1         1            4.0            0            0.0               1.000000           NaN
C.J. Beathard       2021      22            2         2           33.0            0            0.0               1.000000           NaN
Brandon Allen       2022       9            3         3           22.0            0            0.0               1.000000           NaN
Sean Clifford       2023      18            1         1           37.0            0            0.0               1.000000           NaN
Mike Glennon        2016       9           10        11           75.0            1            0.0               0.909091           inf
Kyle Orton          2012       4            9        10           89.0            1            0.0               0.900000           inf
Jeff Blake          2005      19            8         9           55.0            1            0.0               0.888889           inf
Quinn Gray          2008      12            7         8           76.0            1            0.0               0.875000           inf
Josh Johnson        2010      83           14        16          111.0            0            0.0               0.875000           NaN
Sean Mannion        2015      12            6         7           31.0            0            0.0               0.857143           NaN
Nick Mullens        2022      55           21        25          224.0            1            1.0               0.840000           1.0
Kellen Clemens      2015      18            5         6           63.0            1            0.0               0.833333           inf
Brian Hoyer         2022       4            5         6           37.0            0            0.0               0.833333           NaN
Mike White          2023      66            5         6           74.0            1            1.0               0.833333           1.0
Nate Sudfeld        2017      17           19        23          134.0            0            0.0               0.826087           NaN
Landry Jones        2017      44           23        28          239.0            1            1.0               0.821429           1.0
Luke McCown         2015      10           32        39          335.0            0            1.0               0.820513           0.0
Brian Hoyer         2021      55            9        11          227.0            1            0.0               0.818182           inf

And another thing will go here.

In [27]:
sum_QB_stats_ratio_sort=sum_QB_stats.sort_values(by="td_int_ratio",ascending=False)
sum_QB_stats_ratio_sort[:40]

                            week  completions  attempts  passing_yards  passing_tds  interceptions  completion_percentage  td_int_ratio
player_display_name season
Jeff Blake          2005      19            8         9           55.0            1            0.0               0.888889           inf
Jay Fiedler         2005       4            8        13          107.0            1            0.0               0.615385           inf
Quinn Gray          2005      17            8        14          100.0            2            0.0               0.571429           inf
Chris Weinke        2005      31            7        13           64.0            1            0.0               0.538462           inf
Matt Schaub         2005      65           33        64          495.0            4            0.0               0.515625           inf
Charlie Batch       2006      71           30        52          477.0            5            0.0               0.576923           inf
Vinny Testaverde    2006      43            2         3           29.0            1            0.0               0.666667           inf
A.J. Feeley         2006      29           26        38          342.0            3            0.0               0.684211           inf
Todd Collins        2007      62           67       105          888.0            5            0.0               0.638095           inf
Chris Weinke        2007      17           13        22          104.0            1            0.0               0.590909           inf
Craig Nall          2007      17            7        15           88.0            1            0.0               0.466667           inf
Jim Sorgi           2007      55           18        36          132.0            1            0.0               0.500000           inf
Aaron Rodgers       2007      23           20        28          218.0            1            0.0               0.714286           inf
Troy Smith          2007      62           40        76          452.0            2            0.0               0.526316           inf
Quinn Gray          2008      12            7         8           76.0            1            0.0               0.875000           inf
David Carr          2008      24            9        12          115.0            2            0.0               0.750000           inf
Byron Leftwich      2008      37           21        36          303.0            2            0.0               0.583333           inf
Drew Stanton        2008      38            9        17          119.0            1            0.0               0.529412           inf
Troy Smith          2008      57            3         4           82.0            1            0.0               0.750000           inf
David Carr          2009      50           21        33          225.0            1            0.0               0.636364           inf
Mike Vick           2009     113            6        13           86.0            1            0.0               0.461538           inf
Brodie Croyle       2009      26           23        40          230.0            2            0.0               0.575000           inf
Tarvaris Jackson    2009      72           14        21          201.0            1            0.0               0.666667           inf
Brad Smith          2010     144            2         3            6.0            1            0.0               0.666667           inf
Stephen McGee       2010      33           22        44          238.0            2            0.0               0.500000           inf
Jake Delhomme       2011      17           18        28          211.0            1            0.0               0.642857           inf
Matt Leinart        2011      22           10        13           57.0            1            0.0               0.769231           inf
Stephen McGee       2011      16           24        38          182.0            1            0.0               0.631579           inf
Jake Locker         2011      51           34        66          542.0            4            0.0               0.515152           inf
Shaun Hill          2012       3           10        13          172.0            2            0.0               0.769231           inf
Kyle Orton          2012       4            9        10           89.0            1            0.0               0.900000           inf
Matt Moore          2012      18           11        19          131.0            1            0.0               0.578947           inf
Colt McCoy          2012      30            9        17           79.0            1            0.0               0.529412           inf
Tarvaris Jackson    2013      29           10        13          151.0            1            0.0               0.769231           inf
Matt Hasselbeck     2014      40           30        44          301.0            2            0.0               0.681818           inf
Derek Anderson      2014      30           65        97          701.0            5            0.0               0.670103           inf
Chase Daniel        2014      32           16        28          157.0            1            0.0               0.571429           inf
Blaine Gabbert      2014       7            3         7           38.0            1            0.0               0.428571           inf
Brock Osweiler      2014      49            4        10           52.0            1            0.0               0.400000           inf
Jimmy Garoppolo     2014      45           19        27          182.0            1            0.0               0.703704           inf

The above process will now be repeated usi