# **ST 554 Spring 2026 Project Two**
## Created by Cody Ashby on March 17, 2026
### *Testing a Customized Class on a Data Set (Part I)*

To start things off, we'll use a class that performs a quality check for a Spark SQL style dataframe. A handful of modules will need to be imported before implementing this class.

In [1]:
from pyspark.sql import DataFrame
from pyspark.sql import functions as F
from functools import reduce
from pyspark.sql.types import *
import pandas as pd

Before proceeding, we'll need to initiate a Spark session.

In [2]:
from pyspark.sql import SparkSession
spark = SparkSession.builder.master('local[*]').appName('ST 554 Project Two').config('spark.sql.ansi.enabled','false').getOrCreate()

WARNING: Using incubator modules: jdk.incubator.vector
Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
26/03/26 22:56:55 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
26/03/26 22:56:56 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.

Now, we'll import the Python file that contains the class so we can do our quality check.

In [3]:
import SparkDataQualityCheck

We'll use the method that reads in a csv file, namely the air quality data set from our first project, to try this out. We'll also use `pandas` to read in the same file.

In [4]:
pandas_data=pd.read_csv("https://www4.stat.ncsu.edu/online/datasets/air.csv")
data=spark.createDataFrame(pandas_data)

Let's create an instance that allows us to read the csv file from the url address below.

In [5]:
air_data=SparkDataQualityCheck.SparkDataCheck("https://www4.stat.ncsu.edu/online/datasets/air.csv")

An alternative may include downloading the csv file and uploading it to the JupyterHub directory. We can then apply the associated class method to read the data in.

In [6]:
spark_air_data=air_data.read_csv(spark,"air.csv")

Now, we'll test a small handful of the functions defined in the class. Let's try a value check on the temperature.

In [7]:
spark_air_data.value_check("T",0,30)

ERROR! This is not a numeric column!
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+
|_c0|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+
|  0|3/10/2004|2026-03-26 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578|
|  1|3/10/2004|2026-03-26 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255|
|  2|3/10/2004|2026-03-26 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502|
|  3|3/10/2004|2026-03-26 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867|
|  4|3/10/2004|2026-03-26 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888|
|  5|3/10/2004|2026-03-26 23:00:00|   1.2|       1197|      38|     4.7|          750|     89|        1337|     96|        1393|        949|11.2|59.2|0.7848|
|  6|3/11/2004|2026-03-26 00:00:00|   1.2|       1185|      31|     3.6|          690|     62|        1462|     77|        1333|        733|11.3|56.8|0.7603|
|  7|3/11/2004|2026-03-26 01:00:00|   1.0|       1136|      31|     3.3|          672|     62|        1453|     76|        1333|        730|10.7|60.0|0.7702|
|  8|3/11/2004|2026-03-26 02:00:00|   0.9|       1094|      24|     2.3|          609|     45|        1579|     60|        1276|        620|10.7|59.7|0.7648|
|  9|3/11/2004|2026-03-26 03:00:00|   0.6|       1010|      19|     1.7|          561|   -200|        1705|   -200|        1235|        501|10.3|60.2|0.7517|
| 10|3/11/2004|2026-03-26 04:00:00|-200.0|       1011|      14|     1.3|          527|     21|        1818|     34|        1197|        445|10.1|60.5|0.7465|
| 11|3/11/2004|2026-03-26 05:00:00|   0.7|       1066|       8|     1.1|          512|     16|        1918|     28|        1182|        422|11.0|56.2|0.7366|
| 12|3/11/2004|2026-03-26 06:00:00|   0.7|       1052|      16|     1.6|          553|     34|        1738|     48|        1221|        472|10.5|58.1|0.7353|
| 13|3/11/2004|2026-03-26 07:00:00|   1.1|       1144|      29|     3.2|          667|     98|        1490|     82|        1339|        730|10.2|59.6|0.7417|
| 14|3/11/2004|2026-03-26 08:00:00|   2.0|       1333|      64|     8.0|          900|    174|        1136|    112|        1517|       1102|10.8|57.4|0.7408|
| 15|3/11/2004|2026-03-26 09:00:00|   2.2|       1351|      87|     9.5|          960|    129|        1079|    101|        1583|       1028|10.5|60.6|0.7691|
| 16|3/11/2004|2026-03-26 10:00:00|   1.7|       1233|      77|     6.3|          827|    112|        1218|     98|        1446|        860|10.8|58.4|0.7552|
| 17|3/11/2004|2026-03-26 11:00:00|   1.5|       1179|      43|     5.0|          762|     95|        1328|     92|        1362|        671|10.5|57.9|0.7352|
| 18|3/11/2004|2026-03-26 12:00:00|   1.6|       1236|      61|     5.2|          774|    104|        1301|     95|        1401|        664| 9.5|66.8|0.7951|
| 19|3/11/2004|2026-03-26 13:00:00|   1.9|       1286|      63|     7.3|          869|    146|        1162|    112|        1537|        799| 8.3|76.4|0.8393|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+
only showing top 20 rows

26/03/26 22:57:08 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
 Schema: _c0, Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
Expected: _c0 but found:
CSV file: file:///home/jupyter-cashby@ncsu.edu/ST%20554%20Project%20Two/air.csv

Hmm, that was strange. We know for certain that, with the exception for Date and Time, that nearly all of the columns are a numeric type.
Chances are something was typed in wrong when defining this function. I normally would've tried this function with just one number instead of two, like below.

In [8]:
#Here's another example of using the value_check function, but with only one number provided.
spark_air_data.value_check("NO2(GT)",123)

ERROR! This is not a numeric column!
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+
|_c0|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+
|  0|3/10/2004|2026-03-26 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578|
|  1|3/10/2004|2026-03-26 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255|
|  2|3/10/2004|2026-03-26 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502|
|  3|3/10/2004|2026-03-26 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867|
|  4|3/10/2004|2026-03-26 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888|
|  5|3/10/2004|2026-03-26 23:00:00|   1.2|       1197|      38|     4.7|          750|     89|        1337|     96|        1393|        949|11.2|59.2|0.7848|
|  6|3/11/2004|2026-03-26 00:00:00|   1.2|       1185|      31|     3.6|          690|     62|        1462|     77|        1333|        733|11.3|56.8|0.7603|
|  7|3/11/2004|2026-03-26 01:00:00|   1.0|       1136|      31|     3.3|          672|     62|        1453|     76|        1333|        730|10.7|60.0|0.7702|
|  8|3/11/2004|2026-03-26 02:00:00|   0.9|       1094|      24|     2.3|          609|     45|        1579|     60|        1276|        620|10.7|59.7|0.7648|
|  9|3/11/2004|2026-03-26 03:00:00|   0.6|       1010|      19|     1.7|          561|   -200|        1705|   -200|        1235|        501|10.3|60.2|0.7517|
| 10|3/11/2004|2026-03-26 04:00:00|-200.0|       1011|      14|     1.3|          527|     21|        1818|     34|        1197|        445|10.1|60.5|0.7465|
| 11|3/11/2004|2026-03-26 05:00:00|   0.7|       1066|       8|     1.1|          512|     16|        1918|     28|        1182|        422|11.0|56.2|0.7366|
| 12|3/11/2004|2026-03-26 06:00:00|   0.7|       1052|      16|     1.6|          553|     34|        1738|     48|        1221|        472|10.5|58.1|0.7353|
| 13|3/11/2004|2026-03-26 07:00:00|   1.1|       1144|      29|     3.2|          667|     98|        1490|     82|        1339|        730|10.2|59.6|0.7417|
| 14|3/11/2004|2026-03-26 08:00:00|   2.0|       1333|      64|     8.0|          900|    174|        1136|    112|        1517|       1102|10.8|57.4|0.7408|
| 15|3/11/2004|2026-03-26 09:00:00|   2.2|       1351|      87|     9.5|          960|    129|        1079|    101|        1583|       1028|10.5|60.6|0.7691|
| 16|3/11/2004|2026-03-26 10:00:00|   1.7|       1233|      77|     6.3|          827|    112|        1218|     98|        1446|        860|10.8|58.4|0.7552|
| 17|3/11/2004|2026-03-26 11:00:00|   1.5|       1179|      43|     5.0|          762|     95|        1328|     92|        1362|        671|10.5|57.9|0.7352|
| 18|3/11/2004|2026-03-26 12:00:00|   1.6|       1236|      61|     5.2|          774|    104|        1301|     95|        1401|        664| 9.5|66.8|0.7951|
| 19|3/11/2004|2026-03-26 13:00:00|   1.9|       1286|      63|     7.3|          869|    146|        1162|    112|        1537|        799| 8.3|76.4|0.8393|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+
only showing top 20 rows

26/03/26 22:57:43 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
 Schema: _c0, Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
Expected: _c0 but found:
CSV file: file:///home/jupyter-cashby@ncsu.edu/ST%20554%20Project%20Two/air.csv

Let's try using a different function and we'll see what happens?

In [10]:
spark_air_data.missing_check("NOx(GT)")

PySparkAttributeError: [ATTRIBUTE_NOT_SUPPORTED] Attribute `column` is not supported.

Huh. This is quite perplexing for me. I'll try another function just for kicks.

In [12]:
spark_air_data.level_check("Date",["3/10/2004","4/10/2004","5/10/2004","6/10/2004"])

ERROR! This is not a string column!
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+
|_c0|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+
|  0|3/10/2004|2026-03-26 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578|
|  1|3/10/2004|2026-03-26 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255|
|  2|3/10/2004|2026-03-26 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502|
|  3|3/10/2004|2026-03-26 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867|
|  4|3/10/2004|2026-03-26 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888|
|  5|3/10/2004|2026-03-26 23:00:00|   1.2|       1197|      38|     4.7|          750|     89|        1337|     96|        1393|        949|11.2|59.2|0.7848|
|  6|3/11/2004|2026-03-26 00:00:00|   1.2|       1185|      31|     3.6|          690|     62|        1462|     77|        1333|        733|11.3|56.8|0.7603|
|  7|3/11/2004|2026-03-26 01:00:00|   1.0|       1136|      31|     3.3|          672|     62|        1453|     76|        1333|        730|10.7|60.0|0.7702|
|  8|3/11/2004|2026-03-26 02:00:00|   0.9|       1094|      24|     2.3|          609|     45|        1579|     60|        1276|        620|10.7|59.7|0.7648|
|  9|3/11/2004|2026-03-26 03:00:00|   0.6|       1010|      19|     1.7|          561|   -200|        1705|   -200|        1235|        501|10.3|60.2|0.7517|
| 10|3/11/2004|2026-03-26 04:00:00|-200.0|       1011|      14|     1.3|          527|     21|        1818|     34|        1197|        445|10.1|60.5|0.7465|
| 11|3/11/2004|2026-03-26 05:00:00|   0.7|       1066|       8|     1.1|          512|     16|        1918|     28|        1182|        422|11.0|56.2|0.7366|
| 12|3/11/2004|2026-03-26 06:00:00|   0.7|       1052|      16|     1.6|          553|     34|        1738|     48|        1221|        472|10.5|58.1|0.7353|
| 13|3/11/2004|2026-03-26 07:00:00|   1.1|       1144|      29|     3.2|          667|     98|        1490|     82|        1339|        730|10.2|59.6|0.7417|
| 14|3/11/2004|2026-03-26 08:00:00|   2.0|       1333|      64|     8.0|          900|    174|        1136|    112|        1517|       1102|10.8|57.4|0.7408|
| 15|3/11/2004|2026-03-26 09:00:00|   2.2|       1351|      87|     9.5|          960|    129|        1079|    101|        1583|       1028|10.5|60.6|0.7691|
| 16|3/11/2004|2026-03-26 10:00:00|   1.7|       1233|      77|     6.3|          827|    112|        1218|     98|        1446|        860|10.8|58.4|0.7552|
| 17|3/11/2004|2026-03-26 11:00:00|   1.5|       1179|      43|     5.0|          762|     95|        1328|     92|        1362|        671|10.5|57.9|0.7352|
| 18|3/11/2004|2026-03-26 12:00:00|   1.6|       1236|      61|     5.2|          774|    104|        1301|     95|        1401|        664| 9.5|66.8|0.7951|
| 19|3/11/2004|2026-03-26 13:00:00|   1.9|       1286|      63|     7.3|          869|    146|        1162|    112|        1537|        799| 8.3|76.4|0.8393|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+
only showing top 20 rows

26/03/26 23:00:40 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
 Schema: _c0, Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
Expected: _c0 but found:
CSV file: file:///home/jupyter-cashby@ncsu.edu/ST%20554%20Project%20Two/air.csv

Okay, it's clear that I typed in something wrong when defining this class. Maybe we should read in the `pandas` dataframe to see if things will go differently?

In [13]:
pandas_air_data=air_data.read_pandas(spark,pandas_data)

Alright, nothing went wrong there. Let's try a function using this approach.

In [14]:
pandas_air_data.value_check("CO(GT)",1,1.5)

ERROR! This is not a numeric column!
+----------+---------+--------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+
|Unnamed: 0|     Date|    Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|
+----------+---------+--------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+
|         0|3/10/2004|18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578|
|         1|3/10/2004|19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255|
|         2|3/10/2004|20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502|
|         3|3/10/2004|21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867|
|         4|3/10/2004|22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888|
|         5|3/10/2004|23:00:00|   1.2|       1197|      38|     4.7|          750|     89|        1337|     96|        1393|        949|11.2|59.2|0.7848|
|         6|3/11/2004| 0:00:00|   1.2|       1185|      31|     3.6|          690|     62|        1462|     77|        1333|        733|11.3|56.8|0.7603|
|         7|3/11/2004| 1:00:00|   1.0|       1136|      31|     3.3|          672|     62|        1453|     76|        1333|        730|10.7|60.0|0.7702|
|         8|3/11/2004| 2:00:00|   0.9|       1094|      24|     2.3|          609|     45|        1579|     60|        1276|        620|10.7|59.7|0.7648|
|         9|3/11/2004| 3:00:00|   0.6|       1010|      19|     1.7|          561|   -200|        1705|   -200|        1235|        501|10.3|60.2|0.7517|
|        10|3/11/2004| 4:00:00|-200.0|       1011|      14|     1.3|          527|     21|        1818|     34|        1197|        445|10.1|60.5|0.7465|
|        11|3/11/2004| 5:00:00|   0.7|       1066|       8|     1.1|          512|     16|        1918|     28|        1182|        422|11.0|56.2|0.7366|
|        12|3/11/2004| 6:00:00|   0.7|       1052|      16|     1.6|          553|     34|        1738|     48|        1221|        472|10.5|58.1|0.7353|
|        13|3/11/2004| 7:00:00|   1.1|       1144|      29|     3.2|          667|     98|        1490|     82|        1339|        730|10.2|59.6|0.7417|
|        14|3/11/2004| 8:00:00|   2.0|       1333|      64|     8.0|          900|    174|        1136|    112|        1517|       1102|10.8|57.4|0.7408|
|        15|3/11/2004| 9:00:00|   2.2|       1351|      87|     9.5|          960|    129|        1079|    101|        1583|       1028|10.5|60.6|0.7691|
|        16|3/11/2004|10:00:00|   1.7|       1233|      77|     6.3|          827|    112|        1218|     98|        1446|        860|10.8|58.4|0.7552|
|        17|3/11/2004|11:00:00|   1.5|       1179|      43|     5.0|          762|     95|        1328|     92|        1362|        671|10.5|57.9|0.7352|
|        18|3/11/2004|12:00:00|   1.6|       1236|      61|     5.2|          774|    104|        1301|     95|        1401|        664| 9.5|66.8|0.7951|
|        19|3/11/2004|13:00:00|   1.9|       1286|      63|     7.3|          869|    146|        1162|    112|        1537|        799| 8.3|76.4|0.8393|
+----------+---------+--------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+
only showing top 20 rows

How embarassing! Somethiing *definitely* went awry when constructing the `.py` file that contained the class.

### *Practicing pandas-on-spark and Spark SQL on NFL Data (Part II)*

In this portion, we'll utilize `pandas-on-spark` and Spark SQL techniques to perform some basic data analysis on an NFL data set. We'll use the former to read in this data set first.

In [15]:
import pandas as pd
import numpy as np
import pyspark.pandas as ps
from pyspark.sql import SparkSession
spark = SparkSession.builder.master('local[*]').appName('ST 554 Project Two').config('spark.sql.ansi.enabled','false').getOrCreate()

/opt/tljh/user/envs/pySpark3/lib/python3.9/site-packages/pyspark/pandas/__init__.py:43: UserWarning: 'PYARROW_IGNORE_TIMEZONE' environment variable was not set. It is required to set this environment variable to '1' in both driver and executor sides if you use pyarrow>=2.0.0. pandas-on-Spark will set it for you but it does not work if there is a Spark context already launched.
  warnings.warn(

Now, we'll use `pandas` to read in the data set.

In [16]:
NFL_data=pd.read_csv("weekly_nfl_data.csv")
spark_NFL_data=ps.from_pandas(NFL_data)
spark_NFL_data.head()

26/03/26 23:10:35 WARN SparkStringUtils: Truncated the string representation of a plan since it was too large. This behavior can be adjusted by setting 'spark.sql.debug.maxToStringFields'.

    player_id player_name    player_display_name position position_group headshot_url recent_team  season  week season_type opponent_team  completions  attempts  passing_yards  passing_tds  interceptions  sacks  sack_yards  sack_fumbles  sack_fumbles_lost  passing_air_yards  passing_yards_after_catch  passing_first_downs  passing_epa  passing_2pt_conversions  pacr  dakota  carries  rushing_yards  rushing_tds  rushing_fumbles  rushing_fumbles_lost  rushing_first_downs  rushing_epa  rushing_2pt_conversions  receptions  targets  receiving_yards  receiving_tds  receiving_fumbles  receiving_fumbles_lost  receiving_air_yards  receiving_yards_after_catch  receiving_first_downs  receiving_epa  receiving_2pt_conversions  racr  target_share  air_yards_share  wopr  special_teams_tds  fantasy_points  fantasy_points_ppr
0  00-0000003        None  Abdul-Karim al-Jabbar       RB             RB         None         MIA    1999     1         REG           DEN            0         0            0.0            0            0.0    0.0         0.0             0                  0                0.0                        0.0                  0.0          NaN                        0   NaN     NaN       16           60.0            1              0.0                   0.0                  4.0     6.248771                        0           1        1              7.0              0                0.0                     0.0                  0.0                          0.0                    0.0       0.292378                          0   0.0      0.052632              NaN   NaN                0.0            12.7                13.7
1  00-0000003        None  Abdul-Karim al-Jabbar       RB             RB         None         MIA    1999     2         REG           ARI            0         0            0.0            0            0.0    0.0         0.0             0                  0                0.0                        0.0                  0.0          NaN                        0   NaN     NaN        9           33.0            0              0.0                   0.0                  1.0    -1.434950                        0           3        4             18.0              0                0.0                     0.0                  0.0                          0.0                    1.0       0.377009                          0   0.0      0.117647              NaN   NaN                0.0             5.1                 8.1
2  00-0000003        None  Abdul-Karim al-Jabbar       RB             RB         None         MIA    1999     4         REG           BUF            0         0            0.0            0            0.0    0.0         0.0             0                  0                0.0                        0.0                  0.0          NaN                        0   NaN     NaN        3            2.0            0              0.0                   0.0                  0.0    -1.539952                        0           0        1              0.0              0                0.0                     0.0                  0.0                          0.0                    0.0      -0.699578                          0   NaN      0.023810              NaN   NaN                0.0             0.2                 0.2
3  00-0000003        None  Abdul-Karim al-Jabbar       RB             RB         None         CLE    1999     7         REG            LA            0         0            0.0            0            0.0    0.0         0.0             0                  0                0.0                        0.0                  0.0          NaN                        0   NaN     NaN        6           27.0            0              0.0                   0.0                  0.0     0.216051                        0           2        2              8.0              0                0.0                     0.0                  0.0                          0.0                    0.0      -0.228454                          0   0.0      0.050000              NaN   NaN                0.0             3.5                 5.5
4  00-0000003        None  Abdul-Karim al-Jabbar       RB             RB         None         CLE    1999     8         REG            NO            0         0            0.0            0            0.0    0.0         0.0             0                  0                0.0                        0.0                  0.0          NaN                        0   NaN     NaN       13           39.0            0              0.0                   0.0                  2.0    -2.972259                        0           0        0              0.0              0                0.0                     0.0                  0.0                          0.0                    0.0            NaN                          0   NaN           NaN              NaN   NaN                0.0             3.9                 3.9

Below is a list of the column names.

In [17]:
spark_NFL_data.columns

Index(['player_id', 'player_name', 'player_display_name', 'position',
       'position_group', 'headshot_url', 'recent_team', 'season', 'week',
       'season_type', 'opponent_team', 'completions', 'attempts',
       'passing_yards', 'passing_tds', 'interceptions', 'sacks', 'sack_yards',
       'sack_fumbles', 'sack_fumbles_lost', 'passing_air_yards',
       'passing_yards_after_catch', 'passing_first_downs', 'passing_epa',
       'passing_2pt_conversions', 'pacr', 'dakota', 'carries', 'rushing_yards',
       'rushing_tds', 'rushing_fumbles', 'rushing_fumbles_lost',
       'rushing_first_downs', 'rushing_epa', 'rushing_2pt_conversions',
       'receptions', 'targets', 'receiving_yards', 'receiving_tds',
       'receiving_fumbles', 'receiving_fumbles_lost', 'receiving_air_yards',
       'receiving_yards_after_catch', 'receiving_first_downs', 'receiving_epa',
       'receiving_2pt_conversions', 'racr', 'target_share', 'air_yards_share',
       'wopr', 'special_teams_tds', 'fantasy_points', 'fantasy_points_ppr'],
      dtype='object')

Now, we'll collect some statistics involving quarterback players during the regular season from 2005 to 2023. Namely, we're interested in who the quarterback players are (of course), the season, the week in the season, and the number of completions, attempts, passing yards, passing touchdowns, and interceptions.

To begin with, we'll construct a table that is grouped by player and season and find the total and average for the remaining variables above. The first 20 observations are given below.

In [19]:
QB_table=spark_NFL_data.loc[((spark_NFL_data.position == "QB") & (spark_NFL_data.season > 2004) & (spark_NFL_data.season_type == "REG")), ['player_display_name', 'season', 'week', 'completions', 'attempts', 'passing_yards', 'passing_tds', 'interceptions']]
QB_stats=QB_table.groupby(['player_display_name','season']).agg(['sum','mean'])[['completions','attempts','passing_yards','passing_tds','interceptions']]
QB_stats.head(20)

                           completions            attempts            passing_yards             passing_tds           interceptions
                                   sum       mean      sum       mean           sum        mean         sum      mean           sum      mean
player_display_name season
Jeff Blake          2005             8   4.000000        9   4.500000          55.0   27.500000           1  0.500000           0.0  0.000000
Daunte Culpepper    2005           139  19.857143      216  30.857143        1564.0  223.428571           6  0.857143          12.0  1.714286
Kerry Collins       2005           302  20.133333      566  37.733333        3759.0  250.600000          20  1.333333          13.0  0.866667
Tony Banks          2005            14  14.000000       25  25.000000         173.0  173.000000           1  1.000000           2.0  2.000000
Charlie Batch       2005            23   7.666667       36  12.000000         246.0   82.000000           1  0.333333           1.0  0.333333
Jeff Garcia         2005           102  17.000000      173  28.833333         937.0  156.166667           3  0.500000           6.0  1.000000
Doug Flutie         2005             5   1.250000       10   2.500000          29.0    7.250000           0  0.000000           0.0  0.000000
Brett Favre         2005           372  23.250000      607  37.937500        3881.0  242.562500          20  1.250000          29.0  1.812500
Todd Bouman         2005            68  13.600000      122  24.400000         722.0  144.400000           2  0.400000           7.0  1.400000
Brad Johnson        2005           183  16.636364      293  26.636364        1885.0  171.363636          12  1.090909           4.0  0.363636
Brian Griese        2005           112  18.666667      174  29.000000        1136.0  189.333333           7  1.166667           7.0  1.166667
Gus Frerotte        2005           257  16.062500      494  30.875000        2996.0  187.250000          18  1.125000          13.0  0.812500
Kelly Holcomb       2005           155  15.500000      230  23.000000        1509.0  150.900000          10  1.000000           8.0  0.800000
Mark Brunell        2005           262  16.375000      454  28.375000        3050.0  190.625000          23  1.437500          10.0  0.625000
Jay Fiedler         2005             8   4.000000       13   6.500000         107.0   53.500000           1  0.500000           0.0  0.000000
Koy Detmer          2005            32   6.400000       56  11.200000         238.0   47.600000           0  0.000000           3.0  0.600000
Jake Delhomme       2005           262  16.375000      435  27.187500        3421.0  213.812500          24  1.500000          16.0  1.000000
Aaron Brooks        2005           240  18.461538      431  33.153846        2882.0  221.692308          13  1.000000          17.0  1.307692
Trent Dilfer        2005           199  18.090909      333  30.272727        2321.0  211.000000          11  1.000000          12.0  1.090909
Trent Green         2005           317  19.812500      507  31.687500        4014.0  250.875000          17  1.062500          10.0  0.625000

Obviously, there are way more than 20 observations in this table. Let's see the dimensions of the table to get a clear picture of how many total observations there are.

In [20]:
QB_stats.shape

(1456, 10)

We can also create some new variables pertaining to the completion percentage as well as the ratio between touchdowns and interceptions.

In [21]:
QB_stats['completion_percentage']=QB_table.groupby(['player_display_name','season']).completions.sum()/QB_table.groupby(['player_display_name','season']).attempts.sum()
QB_stats['td_int_ratio']=QB_table.groupby(['player_display_name','season']).passing_tds.sum()/QB_table.groupby(['player_display_name','season']).interceptions.sum()

Our final table below contains the grouped sums along with the newly defined variables. Here are the first 40 entries.

In [22]:
QB_stats.head(40)

                           completions            attempts            passing_yards             passing_tds           interceptions           completion_percentage td_int_ratio
                                   sum       mean      sum       mean           sum        mean         sum      mean           sum      mean
player_display_name season
Jeff Blake          2005             8   4.000000        9   4.500000          55.0   27.500000           1  0.500000           0.0  0.000000              0.888889          inf
Daunte Culpepper    2005           139  19.857143      216  30.857143        1564.0  223.428571           6  0.857143          12.0  1.714286              0.643519     0.500000
Kerry Collins       2005           302  20.133333      566  37.733333        3759.0  250.600000          20  1.333333          13.0  0.866667              0.533569     1.538462
Tony Banks          2005            14  14.000000       25  25.000000         173.0  173.000000           1  1.000000           2.0  2.000000              0.560000     0.500000
Charlie Batch       2005            23   7.666667       36  12.000000         246.0   82.000000           1  0.333333           1.0  0.333333              0.638889     1.000000
Jeff Garcia         2005           102  17.000000      173  28.833333         937.0  156.166667           3  0.500000           6.0  1.000000              0.589595     0.500000
Doug Flutie         2005             5   1.250000       10   2.500000          29.0    7.250000           0  0.000000           0.0  0.000000              0.500000          NaN
Brett Favre         2005           372  23.250000      607  37.937500        3881.0  242.562500          20  1.250000          29.0  1.812500              0.612850     0.689655
Todd Bouman         2005            68  13.600000      122  24.400000         722.0  144.400000           2  0.400000           7.0  1.400000              0.557377     0.285714
Brad Johnson        2005           183  16.636364      293  26.636364        1885.0  171.363636          12  1.090909           4.0  0.363636              0.624573     3.000000
Brian Griese        2005           112  18.666667      174  29.000000        1136.0  189.333333           7  1.166667           7.0  1.166667              0.643678     1.000000
Gus Frerotte        2005           257  16.062500      494  30.875000        2996.0  187.250000          18  1.125000          13.0  0.812500              0.520243     1.384615
Kelly Holcomb       2005           155  15.500000      230  23.000000        1509.0  150.900000          10  1.000000           8.0  0.800000              0.673913     1.250000
Mark Brunell        2005           262  16.375000      454  28.375000        3050.0  190.625000          23  1.437500          10.0  0.625000              0.577093     2.300000
Jay Fiedler         2005             8   4.000000       13   6.500000         107.0   53.500000           1  0.500000           0.0  0.000000              0.615385          inf
Koy Detmer          2005            32   6.400000       56  11.200000         238.0   47.600000           0  0.000000           3.0  0.600000              0.571429     0.000000
Jake Delhomme       2005           262  16.375000      435  27.187500        3421.0  213.812500          24  1.500000          16.0  1.000000              0.602299     1.500000
Aaron Brooks        2005           240  18.461538      431  33.153846        2882.0  221.692308          13  1.000000          17.0  1.307692              0.556845     0.764706
Trent Dilfer        2005           199  18.090909      333  30.272727        2321.0  211.000000          11  1.000000          12.0  1.090909              0.597598     0.916667
Trent Green         2005           317  19.812500      507  31.687500        4014.0  250.875000          17  1.062500          10.0  0.625000              0.625247     1.700000
Drew Bledsoe        2005           300  18.750000      499  31.187500        3639.0  227.437500          23  1.437500          17.0  1.062500              0.601202     1.352941
Todd Collins        2005             0   0.000000        0   0.000000           0.0    0.000000           0  0.000000           0.0  0.000000                   NaN          NaN
Matt Hasselbeck     2005           294  18.375000      450  28.125000        3455.0  215.937500          24  1.500000          10.0  0.625000              0.653333     2.400000
Tim Hasselbeck      2005             0   0.000000        0   0.000000           0.0    0.000000           0  0.000000           0.0  0.000000                   NaN          NaN
Tim Rattay          2005            56  14.000000       97  24.250000         667.0  166.750000           5  1.250000           6.0  1.500000              0.577320     0.833333
Kordell Stewart     2005             0   0.000000        0   0.000000           0.0    0.000000           0  0.000000           0.0  0.000000                   NaN          NaN
Jon Kitna           2005            17   5.666667       29   9.666667          99.0   33.000000           0  0.000000           2.0  0.666667              0.586207     0.000000
Tom Brady           2005           334  20.875000      530  33.125000        4110.0  256.875000          26  1.625000          14.0  0.875000              0.630189     1.857143
Steve McNair        2005           292  20.857143      476  34.000000        3161.0  225.785714          16  1.142857          11.0  0.785714              0.613445     1.454545
Jamie Martin        2005           124  15.500000      177  22.125000        1277.0  159.625000           5  0.625000           7.0  0.875000              0.700565     0.714286
Peyton Manning      2005           305  19.062500      453  28.312500        3747.0  234.187500          28  1.750000          10.0  0.625000              0.673289     2.800000
Chad Pennington     2005            49  16.333333       83  27.666667         530.0  176.666667           2  0.666667           3.0  1.000000              0.590361     0.666667
Marc Bulger         2005           192  24.000000      287  35.875000        2297.0  287.125000          14  1.750000           9.0  1.125000              0.668990     1.555556
Donovan McNabb      2005           211  23.444444      357  39.666667        2507.0  278.555556          16  1.777778           9.0  1.000000              0.591036     1.777778
Anthony Wright      2005           164  20.500000      266  33.250000        1582.0  197.750000           6  0.750000           9.0  1.125000              0.616541     0.666667
Billy Volek         2005            50  10.000000       88  17.600000         474.0   94.800000           4  0.800000           2.0  0.400000              0.568182     2.000000
Vinny Testaverde    2005            60  10.000000      106  17.666667         777.0  129.500000           1  0.166667           6.0  1.000000              0.566038     0.166667
Kurt Warner         2005           242  24.200000      375  37.500000        2713.0  271.300000          11  1.100000           9.0  0.900000              0.645333     1.222222
Jake Plummer        2005           277  17.312500      456  28.500000        3366.0  210.375000          18  1.125000           7.0  0.437500              0.607456     2.571429
Tommy Maddox        2005            34  11.333333       71  23.666667         406.0  135.333333           2  0.666667           4.0  1.333333              0.478873     0.500000

Here are the updated dimensions for the table with the new variables added in; of course, nothing changed except the addition of those two variables.

In [23]:
QB_stats.shape

(1456, 12)

Below is a collection of quarterback players that had a total of at least 50 attempts.

In [24]:
QB_stats[QB_stats.attempts['sum'] >= 50].head(50)

                           completions            attempts            passing_yards             passing_tds           interceptions           completion_percentage td_int_ratio
                                   sum       mean      sum       mean           sum        mean         sum      mean           sum      mean
player_display_name season
Daunte Culpepper    2005           139  19.857143      216  30.857143        1564.0  223.428571           6  0.857143          12.0  1.714286              0.643519     0.500000
Kerry Collins       2005           302  20.133333      566  37.733333        3759.0  250.600000          20  1.333333          13.0  0.866667              0.533569     1.538462
Jeff Garcia         2005           102  17.000000      173  28.833333         937.0  156.166667           3  0.500000           6.0  1.000000              0.589595     0.500000
Brett Favre         2005           372  23.250000      607  37.937500        3881.0  242.562500          20  1.250000          29.0  1.812500              0.612850     0.689655
Todd Bouman         2005            68  13.600000      122  24.400000         722.0  144.400000           2  0.400000           7.0  1.400000              0.557377     0.285714
Brad Johnson        2005           183  16.636364      293  26.636364        1885.0  171.363636          12  1.090909           4.0  0.363636              0.624573     3.000000
Brian Griese        2005           112  18.666667      174  29.000000        1136.0  189.333333           7  1.166667           7.0  1.166667              0.643678     1.000000
Gus Frerotte        2005           257  16.062500      494  30.875000        2996.0  187.250000          18  1.125000          13.0  0.812500              0.520243     1.384615
Kelly Holcomb       2005           155  15.500000      230  23.000000        1509.0  150.900000          10  1.000000           8.0  0.800000              0.673913     1.250000
Mark Brunell        2005           262  16.375000      454  28.375000        3050.0  190.625000          23  1.437500          10.0  0.625000              0.577093     2.300000
Koy Detmer          2005            32   6.400000       56  11.200000         238.0   47.600000           0  0.000000           3.0  0.600000              0.571429     0.000000
Jake Delhomme       2005           262  16.375000      435  27.187500        3421.0  213.812500          24  1.500000          16.0  1.000000              0.602299     1.500000
Aaron Brooks        2005           240  18.461538      431  33.153846        2882.0  221.692308          13  1.000000          17.0  1.307692              0.556845     0.764706
Trent Dilfer        2005           199  18.090909      333  30.272727        2321.0  211.000000          11  1.000000          12.0  1.090909              0.597598     0.916667
Trent Green         2005           317  19.812500      507  31.687500        4014.0  250.875000          17  1.062500          10.0  0.625000              0.625247     1.700000
Drew Bledsoe        2005           300  18.750000      499  31.187500        3639.0  227.437500          23  1.437500          17.0  1.062500              0.601202     1.352941
Matt Hasselbeck     2005           294  18.375000      450  28.125000        3455.0  215.937500          24  1.500000          10.0  0.625000              0.653333     2.400000
Tim Rattay          2005            56  14.000000       97  24.250000         667.0  166.750000           5  1.250000           6.0  1.500000              0.577320     0.833333
Tom Brady           2005           334  20.875000      530  33.125000        4110.0  256.875000          26  1.625000          14.0  0.875000              0.630189     1.857143
Steve McNair        2005           292  20.857143      476  34.000000        3161.0  225.785714          16  1.142857          11.0  0.785714              0.613445     1.454545
Jamie Martin        2005           124  15.500000      177  22.125000        1277.0  159.625000           5  0.625000           7.0  0.875000              0.700565     0.714286
Peyton Manning      2005           305  19.062500      453  28.312500        3747.0  234.187500          28  1.750000          10.0  0.625000              0.673289     2.800000
Chad Pennington     2005            49  16.333333       83  27.666667         530.0  176.666667           2  0.666667           3.0  1.000000              0.590361     0.666667
Marc Bulger         2005           192  24.000000      287  35.875000        2297.0  287.125000          14  1.750000           9.0  1.125000              0.668990     1.555556
Donovan McNabb      2005           211  23.444444      357  39.666667        2507.0  278.555556          16  1.777778           9.0  1.000000              0.591036     1.777778
Anthony Wright      2005           164  20.500000      266  33.250000        1582.0  197.750000           6  0.750000           9.0  1.125000              0.616541     0.666667
Billy Volek         2005            50  10.000000       88  17.600000         474.0   94.800000           4  0.800000           2.0  0.400000              0.568182     2.000000
Vinny Testaverde    2005            60  10.000000      106  17.666667         777.0  129.500000           1  0.166667           6.0  1.000000              0.566038     0.166667
Kurt Warner         2005           242  24.200000      375  37.500000        2713.0  271.300000          11  1.100000           9.0  0.900000              0.645333     1.222222
Jake Plummer        2005           277  17.312500      456  28.500000        3366.0  210.375000          18  1.125000           7.0  0.437500              0.607456     2.571429
Tommy Maddox        2005            34  11.333333       71  23.666667         406.0  135.333333           2  0.666667           4.0  1.333333              0.478873     0.500000
David Garrard       2005            98  14.000000      168  24.000000        1117.0  159.571429           4  0.571429           1.0  0.142857              0.583333     4.000000
David Carr          2005           256  16.000000      423  26.437500        2488.0  155.500000          14  0.875000          11.0  0.687500              0.605201     1.272727
Josh McCown         2005           163  18.111111      270  30.000000        1832.0  203.555556           9  1.000000          11.0  1.222222              0.603704     0.818182
Mike McMahon        2005            94  10.444444      207  23.000000        1158.0  128.666667           5  0.555556           8.0  0.888889              0.454106     0.625000
Drew Brees          2005           323  20.187500      500  31.250000        3576.0  223.500000          24  1.500000          15.0  0.937500              0.646000     1.600000
Mike Vick           2005           214  14.266667      387  25.800000        2412.0  160.800000          15  1.000000          13.0  0.866667              0.552972     1.153846
Joey Harrington     2005           188  15.666667      330  27.500000        2021.0  168.416667          12  1.000000          12.0  1.000000              0.569697     1.000000
Sage Rosenfels      2005            34   8.500000       61  15.250000         462.0  115.500000           4  1.000000           3.0  0.750000              0.557377     1.333333
Kyle Boller         2005           171  19.000000      293  32.555556        1799.0  199.888889          11  1.222222          12.0  1.333333              0.583618     0.916667
Jim Sorgi           2005            43   8.600000       62  12.400000         444.0   88.800000           3  0.600000           1.0  0.200000              0.693548     3.000000
Ken Dorsey          2005            48  16.000000       90  30.000000         481.0  160.333333           2  0.666667           2.0  0.666667              0.533333     1.000000
Brooks Bollinger    2005           150  13.636364      266  24.181818        1558.0  141.636364           7  0.636364           6.0  0.545455              0.563910     1.166667
Carson Palmer       2005           345  21.562500      509  31.812500        3836.0  239.750000          32  2.000000          12.0  0.750000              0.677800     2.666667
Chris Simms         2005           191  17.363636      313  28.454545        2035.0  185.000000          10  0.909091           7.0  0.636364              0.610224     1.428571
Byron Leftwich      2005           175  15.909091      302  27.454545        2123.0  193.000000          15  1.363636           5.0  0.454545              0.579470     3.000000
Drew Bledsoe        2006            90  15.000000      169  28.166667        1164.0  194.000000           7  1.166667           8.0  1.333333              0.532544     0.875000
J.P. Losman         2005           114  12.666667      228  25.333333        1340.0  148.888889           8  0.888889           8.0  0.888889              0.500000     1.000000
Ryan Fitzpatrick    2005            76  19.000000      135  33.750000         777.0  194.250000           4  1.000000           8.0  2.000000              0.562963     0.500000
Ben Roethlisberger  2005           168  14.000000      268  22.333333        2385.0  198.750000          17  1.416667           9.0  0.750000              0.626866     1.888889

Below are the dimensions of this subsetted data; here, we see that slightly less than two-thirds of all the quarterback players have made a total of at least 50 attempts.

In [25]:
QB_stats[QB_stats.attempts['sum'] >= 50].shape

(966, 12)

Next up is the table sorted by descending completion percentage. Only the first 40 are listed here.

In [26]:
QB_stats_percent_sort=QB_stats.sort_values(by="completion_percentage",ascending=False)
QB_stats_percent_sort[:40]

                           completions            attempts            passing_yards             passing_tds           interceptions           completion_percentage td_int_ratio
                                   sum       mean      sum       mean           sum        mean         sum      mean           sum      mean
player_display_name season
Anthony Wright      2006             3   1.500000        3   1.500000          31.0   15.500000           0  0.000000           0.0  0.000000              1.000000          NaN
Matt Gutierrez      2007             1   0.250000        1   0.250000          15.0    3.750000           0  0.000000           0.0  0.000000              1.000000          NaN
Dennis Dixon        2008             1   1.000000        1   1.000000           3.0    3.000000           0  0.000000           0.0  0.000000              1.000000          NaN
Matt Gutierrez      2009             1   1.000000        1   1.000000           3.0    3.000000           0  0.000000           0.0  0.000000              1.000000          NaN
Brad Smith          2009             1   0.090909        1   0.090909          27.0    2.454545           0  0.000000           0.0  0.000000              1.000000          NaN
Billy Volek         2010             1   0.333333        1   0.333333           8.0    2.666667           0  0.000000           0.0  0.000000              1.000000          NaN
Jordan Palmer       2010             3   3.000000        3   3.000000          18.0   18.000000           0  0.000000           0.0  0.000000              1.000000          NaN
Brian Hoyer         2011             1   0.500000        1   0.500000          22.0   11.000000           0  0.000000           0.0  0.000000              1.000000          NaN
Tyrod Taylor        2011             1   0.500000        1   0.500000          18.0    9.000000           0  0.000000           0.0  0.000000              1.000000          NaN
Derek Anderson      2012             4   2.000000        4   2.000000          58.0   29.000000           0  0.000000           0.0  0.000000              1.000000          NaN
Trent Edwards       2012             2   2.000000        2   2.000000          14.0   14.000000           0  0.000000           0.0  0.000000              1.000000          NaN
Chase Daniel        2012             1   1.000000        1   1.000000          10.0   10.000000           0  0.000000           0.0  0.000000              1.000000          NaN
Colt McCoy          2013             1   0.333333        1   0.333333          13.0    4.333333           0  0.000000           0.0  0.000000              1.000000          NaN
Tarvaris Jackson    2014             1   1.000000        1   1.000000           0.0    0.000000           0  0.000000           0.0  0.000000              1.000000          NaN
Matt Moore          2015             1   1.000000        1   1.000000          14.0   14.000000           0  0.000000           0.0  0.000000              1.000000          NaN
Chase Daniel        2015             2   1.000000        2   1.000000           4.0    2.000000           0  0.000000           0.0  0.000000              1.000000          NaN
Scott Tolzien       2015             1   0.500000        1   0.500000           4.0    2.000000           0  0.000000           0.0  0.000000              1.000000          NaN
Ryan Nassib         2015             5   5.000000        5   5.000000          68.0   68.000000           1  1.000000           0.0  0.000000              1.000000          inf
Chase Daniel        2016             1   1.000000        1   1.000000          16.0   16.000000           0  0.000000           0.0  0.000000              1.000000          NaN
Taylor Heinicke     2017             1   1.000000        1   1.000000          10.0   10.000000           0  0.000000           0.0  0.000000              1.000000          NaN
Alex Tanney         2019             1   1.000000        1   1.000000           1.0    1.000000           0  0.000000           0.0  0.000000              1.000000          NaN
AJ McCarron         2020             1   0.500000        1   0.500000          20.0   10.000000           0  0.000000           0.0  0.000000              1.000000          NaN
Easton Stick        2020             1   1.000000        1   1.000000           4.0    4.000000           0  0.000000           0.0  0.000000              1.000000          NaN
C.J. Beathard       2021             2   1.000000        2   1.000000          33.0   16.500000           0  0.000000           0.0  0.000000              1.000000          NaN
Brandon Allen       2022             3   3.000000        3   3.000000          22.0   22.000000           0  0.000000           0.0  0.000000              1.000000          NaN
Sean Clifford       2023             1   0.500000        1   0.500000          37.0   18.500000           0  0.000000           0.0  0.000000              1.000000          NaN
Mike Glennon        2016            10  10.000000       11  11.000000          75.0   75.000000           1  1.000000           0.0  0.000000              0.909091          inf
Kyle Orton          2012             9   9.000000       10  10.000000          89.0   89.000000           1  1.000000           0.0  0.000000              0.900000          inf
Jeff Blake          2005             8   4.000000        9   4.500000          55.0   27.500000           1  0.500000           0.0  0.000000              0.888889          inf
Quinn Gray          2008             7   7.000000        8   8.000000          76.0   76.000000           1  1.000000           0.0  0.000000              0.875000          inf
Josh Johnson        2010            14   1.750000       16   2.000000         111.0   13.875000           0  0.000000           0.0  0.000000              0.875000          NaN
Sean Mannion        2015             6   6.000000        7   7.000000          31.0   31.000000           0  0.000000           0.0  0.000000              0.857143          NaN
Nick Mullens        2022            21   5.250000       25   6.250000         224.0   56.000000           1  0.250000           1.0  0.250000              0.840000          1.0
Kellen Clemens      2015             5   2.500000        6   3.000000          63.0   31.500000           1  0.500000           0.0  0.000000              0.833333          inf
Brian Hoyer         2022             5   5.000000        6   6.000000          37.0   37.000000           0  0.000000           0.0  0.000000              0.833333          NaN
Mike White          2023             5   0.833333        6   1.000000          74.0   12.333333           1  0.166667           1.0  0.166667              0.833333          1.0
Nate Sudfeld        2017            19  19.000000       23  23.000000         134.0  134.000000           0  0.000000           0.0  0.000000              0.826087          NaN
Landry Jones        2017            23   7.666667       28   9.333333         239.0   79.666667           1  0.333333           1.0  0.333333              0.821429          1.0
Luke McCown         2015            32  16.000000       39  19.500000         335.0  167.500000           0  0.000000           1.0  0.500000              0.820513          0.0
Brian Hoyer         2021             9   1.800000       11   2.200000         227.0   45.400000           1  0.200000           0.0  0.000000              0.818182          inf

Lastly, we have the table sorted by descending passing touchdown to interception ratio. Again, only the first 40 entries are listed.

In [27]:
QB_stats_ratio_sort=QB_stats.sort_values(by="td_int_ratio",ascending=False)
QB_stats_ratio_sort[:40]

                           completions            attempts            passing_yards             passing_tds           interceptions      completion_percentage td_int_ratio
                                   sum       mean      sum       mean           sum        mean         sum      mean           sum mean
player_display_name season
Jeff Blake          2005             8   4.000000        9   4.500000          55.0   27.500000           1  0.500000           0.0  0.0              0.888889          inf
Jay Fiedler         2005             8   4.000000       13   6.500000         107.0   53.500000           1  0.500000           0.0  0.0              0.615385          inf
Quinn Gray          2005             8   8.000000       14  14.000000         100.0  100.000000           2  2.000000           0.0  0.0              0.571429          inf
Chris Weinke        2005             7   2.333333       13   4.333333          64.0   21.333333           1  0.333333           0.0  0.0              0.538462          inf
Matt Schaub         2005            33   4.714286       64   9.142857         495.0   70.714286           4  0.571429           0.0  0.0              0.515625          inf
Charlie Batch       2006            30   4.285714       52   7.428571         477.0   68.142857           5  0.714286           0.0  0.0              0.576923          inf
Vinny Testaverde    2006             2   0.666667        3   1.000000          29.0    9.666667           1  0.333333           0.0  0.0              0.666667          inf
A.J. Feeley         2006            26  13.000000       38  19.000000         342.0  171.000000           3  1.500000           0.0  0.0              0.684211          inf
Todd Collins        2007            67  16.750000      105  26.250000         888.0  222.000000           5  1.250000           0.0  0.0              0.638095          inf
Chris Weinke        2007            13  13.000000       22  22.000000         104.0  104.000000           1  1.000000           0.0  0.0              0.590909          inf
Craig Nall          2007             7   7.000000       15  15.000000          88.0   88.000000           1  1.000000           0.0  0.0              0.466667          inf
Jim Sorgi           2007            18   4.500000       36   9.000000         132.0   33.000000           1  0.250000           0.0  0.0              0.500000          inf
Aaron Rodgers       2007            20  10.000000       28  14.000000         218.0  109.000000           1  0.500000           0.0  0.0              0.714286          inf
Troy Smith          2007            40  10.000000       76  19.000000         452.0  113.000000           2  0.500000           0.0  0.0              0.526316          inf
Quinn Gray          2008             7   7.000000        8   8.000000          76.0   76.000000           1  1.000000           0.0  0.0              0.875000          inf
David Carr          2008             9   3.000000       12   4.000000         115.0   38.333333           2  0.666667           0.0  0.0              0.750000          inf
Byron Leftwich      2008            21   4.200000       36   7.200000         303.0   60.600000           2  0.400000           0.0  0.0              0.583333          inf
Drew Stanton        2008             9   3.000000       17   5.666667         119.0   39.666667           1  0.333333           0.0  0.0              0.529412          inf
Troy Smith          2008             3   0.600000        4   0.800000          82.0   16.400000           1  0.200000           0.0  0.0              0.750000          inf
David Carr          2009            21   3.500000       33   5.500000         225.0   37.500000           1  0.166667           0.0  0.0              0.636364          inf
Mike Vick           2009             6   0.500000       13   1.083333          86.0    7.166667           1  0.083333           0.0  0.0              0.461538          inf
Brodie Croyle       2009            23   7.666667       40  13.333333         230.0   76.666667           2  0.666667           0.0  0.0              0.575000          inf
Tarvaris Jackson    2009            14   1.750000       21   2.625000         201.0   25.125000           1  0.125000           0.0  0.0              0.666667          inf
Brad Smith          2010             2   0.133333        3   0.200000           6.0    0.400000           1  0.066667           0.0  0.0              0.666667          inf
Stephen McGee       2010            22  11.000000       44  22.000000         238.0  119.000000           2  1.000000           0.0  0.0              0.500000          inf
Jake Delhomme       2011            18  18.000000       28  28.000000         211.0  211.000000           1  1.000000           0.0  0.0              0.642857          inf
Matt Leinart        2011            10   5.000000       13   6.500000          57.0   28.500000           1  0.500000           0.0  0.0              0.769231          inf
Stephen McGee       2011            24  24.000000       38  38.000000         182.0  182.000000           1  1.000000           0.0  0.0              0.631579          inf
Jake Locker         2011            34   6.800000       66  13.200000         542.0  108.400000           4  0.800000           0.0  0.0              0.515152          inf
Shaun Hill          2012            10  10.000000       13  13.000000         172.0  172.000000           2  2.000000           0.0  0.0              0.769231          inf
Kyle Orton          2012             9   9.000000       10  10.000000          89.0   89.000000           1  1.000000           0.0  0.0              0.900000          inf
Matt Moore          2012            11   5.500000       19   9.500000         131.0   65.500000           1  0.500000           0.0  0.0              0.578947          inf
Colt McCoy          2012             9   4.500000       17   8.500000          79.0   39.500000           1  0.500000           0.0  0.0              0.529412          inf
Tarvaris Jackson    2013            10   3.333333       13   4.333333         151.0   50.333333           1  0.333333           0.0  0.0              0.769231          inf
Matt Hasselbeck     2014            30   7.500000       44  11.000000         301.0   75.250000           2  0.500000           0.0  0.0              0.681818          inf
Derek Anderson      2014            65  13.000000       97  19.400000         701.0  140.200000           5  1.000000           0.0  0.0              0.670103          inf
Chase Daniel        2014            16   8.000000       28  14.000000         157.0   78.500000           1  0.500000           0.0  0.0              0.571429          inf
Blaine Gabbert      2014             3   3.000000        7   7.000000          38.0   38.000000           1  1.000000           0.0  0.0              0.428571          inf
Brock Osweiler      2014             4   1.000000       10   2.500000          52.0   13.000000           1  0.250000           0.0  0.0              0.400000          inf
Jimmy Garoppolo     2014            19   3.800000       27   5.400000         182.0   36.400000           1  0.200000           0.0  0.0              0.703704          inf

Now, we'll repeat this entire process using Spark SQL techniques, including reading in the data. Let's define our Spark session first.

In [28]:
from pyspark.sql import SparkSession
spark = SparkSession.builder.master('local[*]').appName('ST 554 Project Two').config('spark.sql.ansi.enabled','false').getOrCreate()

Now, we can read in the data using commands from Spark.

In [29]:
spark2_NFL_data=spark.read.load("weekly_nfl_data.csv",format = "csv",inferSchema = "true",header = "true")

In order to see the first few entries for this data set, the `head()` function will not work here since we're not utilizing `pandas` from this point forward. Although a little messy, the `show()` and `take()` methods accomplish the same goal.

In [30]:
spark2_NFL_data.take(5)

[Row(player_id='00-0000003', player_name=None, player_display_name='Abdul-Karim al-Jabbar', position='RB', position_group='RB', headshot_url=None, recent_team='MIA', season=1999, week=1, season_type='REG', opponent_team='DEN', completions=0, attempts=0, passing_yards=0.0, passing_tds=0, interceptions=0.0, sacks=0.0, sack_yards=0.0, sack_fumbles=0, sack_fumbles_lost=0, passing_air_yards=0.0, passing_yards_after_catch=0.0, passing_first_downs=0.0, passing_epa=None, passing_2pt_conversions=0, pacr=None, dakota=None, carries=16, rushing_yards=60.0, rushing_tds=1, rushing_fumbles=0.0, rushing_fumbles_lost=0.0, rushing_first_downs=4.0, rushing_epa=6.248771, rushing_2pt_conversions=0, receptions=1, targets=1, receiving_yards=7.0, receiving_tds=0, receiving_fumbles=0.0, receiving_fumbles_lost=0.0, receiving_air_yards=0.0, receiving_yards_after_catch=0.0, receiving_first_downs=0.0, receiving_epa=0.29237816, receiving_2pt_conversions=0, racr=0.0, target_share=0.05263158, air_yards_share=None, wopr=None, special_teams_tds=0.0, fantasy_points=12.7, fantasy_points_ppr=13.7),
 Row(player_id='00-0000003', player_name=None, player_display_name='Abdul-Karim al-Jabbar', position='RB', position_group='RB', headshot_url=None, recent_team='MIA', season=1999, week=2, season_type='REG', opponent_team='ARI', completions=0, attempts=0, passing_yards=0.0, passing_tds=0, interceptions=0.0, sacks=0.0, sack_yards=0.0, sack_fumbles=0, sack_fumbles_lost=0, passing_air_yards=0.0, passing_yards_after_catch=0.0, passing_first_downs=0.0, passing_epa=None, passing_2pt_conversions=0, pacr=None, dakota=None, carries=9, rushing_yards=33.0, rushing_tds=0, rushing_fumbles=0.0, rushing_fumbles_lost=0.0, rushing_first_downs=1.0, rushing_epa=-1.4349501, rushing_2pt_conversions=0, receptions=3, targets=4, receiving_yards=18.0, receiving_tds=0, receiving_fumbles=0.0, receiving_fumbles_lost=0.0, receiving_air_yards=0.0, receiving_yards_after_catch=0.0, receiving_first_downs=1.0, receiving_epa=0.3770089, receiving_2pt_conversions=0, racr=0.0, target_share=0.11764706, air_yards_share=None, wopr=None, special_teams_tds=0.0, fantasy_points=5.1, fantasy_points_ppr=8.1),
 Row(player_id='00-0000003', player_name=None, player_display_name='Abdul-Karim al-Jabbar', position='RB', position_group='RB', headshot_url=None, recent_team='MIA', season=1999, week=4, season_type='REG', opponent_team='BUF', completions=0, attempts=0, passing_yards=0.0, passing_tds=0, interceptions=0.0, sacks=0.0, sack_yards=0.0, sack_fumbles=0, sack_fumbles_lost=0, passing_air_yards=0.0, passing_yards_after_catch=0.0, passing_first_downs=0.0, passing_epa=None, passing_2pt_conversions=0, pacr=None, dakota=None, carries=3, rushing_yards=2.0, rushing_tds=0, rushing_fumbles=0.0, rushing_fumbles_lost=0.0, rushing_first_downs=0.0, rushing_epa=-1.5399517, rushing_2pt_conversions=0, receptions=0, targets=1, receiving_yards=0.0, receiving_tds=0, receiving_fumbles=0.0, receiving_fumbles_lost=0.0, receiving_air_yards=0.0, receiving_yards_after_catch=0.0, receiving_first_downs=0.0, receiving_epa=-0.69957775, receiving_2pt_conversions=0, racr=None, target_share=0.023809524, air_yards_share=None, wopr=None, special_teams_tds=0.0, fantasy_points=0.2, fantasy_points_ppr=0.2),
 Row(player_id='00-0000003', player_name=None, player_display_name='Abdul-Karim al-Jabbar', position='RB', position_group='RB', headshot_url=None, recent_team='CLE', season=1999, week=7, season_type='REG', opponent_team='LA', completions=0, attempts=0, passing_yards=0.0, passing_tds=0, interceptions=0.0, sacks=0.0, sack_yards=0.0, sack_fumbles=0, sack_fumbles_lost=0, passing_air_yards=0.0, passing_yards_after_catch=0.0, passing_first_downs=0.0, passing_epa=None, passing_2pt_conversions=0, pacr=None, dakota=None, carries=6, rushing_yards=27.0, rushing_tds=0, rushing_fumbles=0.0, rushing_fumbles_lost=0.0, rushing_first_downs=0.0, rushing_epa=0.2160509, rushing_2pt_conversions=0, receptions=2, targets=2, receiving_yards=8.0, receiving_tds=0, receiving_fumbles=0.0, receiving_fumbles_lost=0.0, receiving_air_yards=0.0, receiving_yards_after_catch=0.0, receiving_first_downs=0.0, receiving_epa=-0.22845396, receiving_2pt_conversions=0, racr=0.0, target_share=0.05, air_yards_share=None, wopr=None, special_teams_tds=0.0, fantasy_points=3.5, fantasy_points_ppr=5.5),
 Row(player_id='00-0000003', player_name=None, player_display_name='Abdul-Karim al-Jabbar', position='RB', position_group='RB', headshot_url=None, recent_team='CLE', season=1999, week=8, season_type='REG', opponent_team='NO', completions=0, attempts=0, passing_yards=0.0, passing_tds=0, interceptions=0.0, sacks=0.0, sack_yards=0.0, sack_fumbles=0, sack_fumbles_lost=0, passing_air_yards=0.0, passing_yards_after_catch=0.0, passing_first_downs=0.0, passing_epa=None, passing_2pt_conversions=0, pacr=None, dakota=None, carries=13, rushing_yards=39.0, rushing_tds=0, rushing_fumbles=0.0, rushing_fumbles_lost=0.0, rushing_first_downs=2.0, rushing_epa=-2.9722588, rushing_2pt_conversions=0, receptions=0, targets=0, receiving_yards=0.0, receiving_tds=0, receiving_fumbles=0.0, receiving_fumbles_lost=0.0, receiving_air_yards=0.0, receiving_yards_after_catch=0.0, receiving_first_downs=0.0, receiving_epa=None, receiving_2pt_conversions=0, racr=None, target_share=None, air_yards_share=None, wopr=None, special_teams_tds=0.0, fantasy_points=3.9, fantasy_points_ppr=3.9)]

However, we can still use the `columns` attribute like we did with the `pandas` functionality. The output will look a tad different, though.

In [31]:
spark2_NFL_data.columns

['player_id',
 'player_name',
 'player_display_name',
 'position',
 'position_group',
 'headshot_url',
 'recent_team',
 'season',
 'week',
 'season_type',
 'opponent_team',
 'completions',
 'attempts',
 'passing_yards',
 'passing_tds',
 'interceptions',
 'sacks',
 'sack_yards',
 'sack_fumbles',
 'sack_fumbles_lost',
 'passing_air_yards',
 'passing_yards_after_catch',
 'passing_first_downs',
 'passing_epa',
 'passing_2pt_conversions',
 'pacr',
 'dakota',
 'carries',
 'rushing_yards',
 'rushing_tds',
 'rushing_fumbles',
 'rushing_fumbles_lost',
 'rushing_first_downs',
 'rushing_epa',
 'rushing_2pt_conversions',
 'receptions',
 'targets',
 'receiving_yards',
 'receiving_tds',
 'receiving_fumbles',
 'receiving_fumbles_lost',
 'receiving_air_yards',
 'receiving_yards_after_catch',
 'receiving_first_downs',
 'receiving_epa',
 'receiving_2pt_conversions',
 'racr',
 'target_share',
 'air_yards_share',
 'wopr',
 'special_teams_tds',
 'fantasy_points',
 'fantasy_points_ppr']

Now, we'll use SQL to get our collection of quarterback stats that we got earlier. Because of this, different functions were used to get what was desired First, we'll deal with collecting the sums for our variables. By default, only the first 20 entries are shown.

In [32]:
sum_QB_stats2=spark2_NFL_data.select('player_display_name','season','week','completions','attempts','passing_yards','passing_tds','interceptions') \
               .filter((spark2_NFL_data.position == "QB") & (spark2_NFL_data.season > 2004) & (spark2_NFL_data.season_type == "REG")) \
               .groupBy(['player_display_name','season']).sum('completions','attempts','passing_yards','passing_tds','interceptions')
sum_QB_stats2.show()

+-------------------+------+----------------+-------------+------------------+----------------+------------------+
|player_display_name|season|sum(completions)|sum(attempts)|sum(passing_yards)|sum(passing_tds)|sum(interceptions)|
+-------------------+------+----------------+-------------+------------------+----------------+------------------+
|      Jake Delhomme|  2006|             263|          431|            2805.0|              17|              11.0|
|       Jake Plummer|  2005|             277|          456|            3366.0|              18|               7.0|
|        Matt Schaub|  2006|              18|           27|             208.0|               1|               2.0|
|        Vince Young|  2006|             184|          356|            2199.0|              12|              13.0|
|      Kerry Collins|  2007|              50|           82|             531.0|               0|               0.0|
|       Todd Collins|  2005|               0|            0|               0.0|               0|               0.0|
|      Charlie Batch|  2006|              30|           52|             477.0|               5|               0.0|
|        Eli Manning|  2006|             301|          522|            3244.0|              25|              18.0|
|        A.J. Feeley|  2006|              26|           38|             342.0|               3|               0.0|
|       Mark Brunell|  2006|             162|          261|            1789.0|               8|               4.0|
|         Shaun Hill|  2007|              54|           80|             501.0|               5|               2.0|
|       Aaron Brooks|  2006|             110|          192|            1105.0|               3|               8.0|
|        Brett Favre|  2006|             343|          613|            3885.0|              18|              18.0|
|         Drew Brees|  2007|             443|          655|            4428.0|              28|              18.0|
|   Bruce Gradkowski|  2006|             177|          328|            1661.0|               9|               9.0|
|    Matt Hasselbeck|  2005|             294|          450|            3455.0|              24|              10.0|
|          Tony Romo|  2005|               0|            0|               0.0|               0|               0.0|
|     Patrick Ramsey|  2005|              15|           25|             279.0|               1|               1.0|
|       Tommy Maddox|  2005|              34|           71|             406.0|               2|               4.0|
|       Jamie Martin|  2006|              16|           24|             208.0|               1|               1.0|
+-------------------+------+----------------+-------------+------------------+----------------+------------------+
only showing top 20 rows

Next, we'll tackle the averages here. Second verse, similar to the first, so to speak.

In [33]:
average_QB_stats2=spark2_NFL_data.select('player_display_name','season','week','completions','attempts','passing_yards','passing_tds','interceptions') \
               .filter((spark2_NFL_data.position == "QB") & (spark2_NFL_data.season > 2004) & (spark2_NFL_data.season_type == "REG")) \
               .groupBy(['player_display_name','season']).mean('completions','attempts','passing_yards','passing_tds','interceptions')
average_QB_stats2.show()

+-------------------+------+------------------+------------------+------------------+------------------+------------------+
|player_display_name|season|  avg(completions)|     avg(attempts)|avg(passing_yards)|  avg(passing_tds)|avg(interceptions)|
+-------------------+------+------------------+------------------+------------------+------------------+------------------+
|      Jake Delhomme|  2006| 20.23076923076923| 33.15384615384615|215.76923076923077|1.3076923076923077|0.8461538461538461|
|       Jake Plummer|  2005|           17.3125|              28.5|           210.375|             1.125|            0.4375|
|        Matt Schaub|  2006|               3.6|               5.4|              41.6|               0.2|               0.4|
|        Vince Young|  2006|12.266666666666667|23.733333333333334|             146.6|               0.8|0.8666666666666667|
|      Kerry Collins|  2007| 8.333333333333334|13.666666666666666|              88.5|               0.0|               0.0|
|       Todd Collins|  2005|               0.0|               0.0|               0.0|               0.0|               0.0|
|      Charlie Batch|  2006| 4.285714285714286| 7.428571428571429| 68.14285714285714|0.7142857142857143|               0.0|
|        Eli Manning|  2006|           18.8125|            32.625|            202.75|            1.5625|             1.125|
|        A.J. Feeley|  2006|              13.0|              19.0|             171.0|               1.5|               0.0|
|       Mark Brunell|  2006|              16.2|              26.1|             178.9|               0.8|               0.4|
|         Shaun Hill|  2007|              18.0|26.666666666666668|             167.0|1.6666666666666667|0.6666666666666666|
|       Aaron Brooks|  2006|             13.75|              24.0|           138.125|             0.375|               1.0|
|        Brett Favre|  2006|           21.4375|           38.3125|          242.8125|             1.125|             1.125|
|         Drew Brees|  2007|           27.6875|           40.9375|            276.75|              1.75|             1.125|
|   Bruce Gradkowski|  2006|13.615384615384615| 25.23076923076923|127.76923076923077|0.6923076923076923|0.6923076923076923|
|    Matt Hasselbeck|  2005|            18.375|            28.125|          215.9375|               1.5|             0.625|
|          Tony Romo|  2005|               0.0|               0.0|               0.0|               0.0|               0.0|
|     Patrick Ramsey|  2005|              3.75|              6.25|             69.75|              0.25|              0.25|
|       Tommy Maddox|  2005|11.333333333333334|23.666666666666668|135.33333333333334|0.6666666666666666|1.3333333333333333|
|       Jamie Martin|  2006|              16.0|              24.0|             208.0|               1.0|               1.0|
+-------------------+------+------------------+------------------+------------------+------------------+------------------+
only showing top 20 rows

We can merge our two tables above by using a `join` method. Here, using `take` appeared to be the less jarring function to use, visually speaking.

In [34]:
QB_stats2=sum_QB_stats2.join(average_QB_stats2,on=['player_display_name','season'])
QB_stats2.take(20)

[Row(player_display_name='Jake Delhomme', season=2006, sum(completions)=263, sum(attempts)=431, sum(passing_yards)=2805.0, sum(passing_tds)=17, sum(interceptions)=11.0, avg(completions)=20.23076923076923, avg(attempts)=33.15384615384615, avg(passing_yards)=215.76923076923077, avg(passing_tds)=1.3076923076923077, avg(interceptions)=0.8461538461538461),
 Row(player_display_name='Jake Plummer', season=2005, sum(completions)=277, sum(attempts)=456, sum(passing_yards)=3366.0, sum(passing_tds)=18, sum(interceptions)=7.0, avg(completions)=17.3125, avg(attempts)=28.5, avg(passing_yards)=210.375, avg(passing_tds)=1.125, avg(interceptions)=0.4375),
 Row(player_display_name='Matt Schaub', season=2006, sum(completions)=18, sum(attempts)=27, sum(passing_yards)=208.0, sum(passing_tds)=1, sum(interceptions)=2.0, avg(completions)=3.6, avg(attempts)=5.4, avg(passing_yards)=41.6, avg(passing_tds)=0.2, avg(interceptions)=0.4),
 Row(player_display_name='Vince Young', season=2006, sum(completions)=184, sum(attempts)=356, sum(passing_yards)=2199.0, sum(passing_tds)=12, sum(interceptions)=13.0, avg(completions)=12.266666666666667, avg(attempts)=23.733333333333334, avg(passing_yards)=146.6, avg(passing_tds)=0.8, avg(interceptions)=0.8666666666666667),
 Row(player_display_name='Kerry Collins', season=2007, sum(completions)=50, sum(attempts)=82, sum(passing_yards)=531.0, sum(passing_tds)=0, sum(interceptions)=0.0, avg(completions)=8.333333333333334, avg(attempts)=13.666666666666666, avg(passing_yards)=88.5, avg(passing_tds)=0.0, avg(interceptions)=0.0),
 Row(player_display_name='Todd Collins', season=2005, sum(completions)=0, sum(attempts)=0, sum(passing_yards)=0.0, sum(passing_tds)=0, sum(interceptions)=0.0, avg(completions)=0.0, avg(attempts)=0.0, avg(passing_yards)=0.0, avg(passing_tds)=0.0, avg(interceptions)=0.0),
 Row(player_display_name='Charlie Batch', season=2006, sum(completions)=30, sum(attempts)=52, sum(passing_yards)=477.0, sum(passing_tds)=5, sum(interceptions)=0.0, avg(completions)=4.285714285714286, avg(attempts)=7.428571428571429, avg(passing_yards)=68.14285714285714, avg(passing_tds)=0.7142857142857143, avg(interceptions)=0.0),
 Row(player_display_name='Eli Manning', season=2006, sum(completions)=301, sum(attempts)=522, sum(passing_yards)=3244.0, sum(passing_tds)=25, sum(interceptions)=18.0, avg(completions)=18.8125, avg(attempts)=32.625, avg(passing_yards)=202.75, avg(passing_tds)=1.5625, avg(interceptions)=1.125),
 Row(player_display_name='A.J. Feeley', season=2006, sum(completions)=26, sum(attempts)=38, sum(passing_yards)=342.0, sum(passing_tds)=3, sum(interceptions)=0.0, avg(completions)=13.0, avg(attempts)=19.0, avg(passing_yards)=171.0, avg(passing_tds)=1.5, avg(interceptions)=0.0),
 Row(player_display_name='Mark Brunell', season=2006, sum(completions)=162, sum(attempts)=261, sum(passing_yards)=1789.0, sum(passing_tds)=8, sum(interceptions)=4.0, avg(completions)=16.2, avg(attempts)=26.1, avg(passing_yards)=178.9, avg(passing_tds)=0.8, avg(interceptions)=0.4),
 Row(player_display_name='Shaun Hill', season=2007, sum(completions)=54, sum(attempts)=80, sum(passing_yards)=501.0, sum(passing_tds)=5, sum(interceptions)=2.0, avg(completions)=18.0, avg(attempts)=26.666666666666668, avg(passing_yards)=167.0, avg(passing_tds)=1.6666666666666667, avg(interceptions)=0.6666666666666666),
 Row(player_display_name='Aaron Brooks', season=2006, sum(completions)=110, sum(attempts)=192, sum(passing_yards)=1105.0, sum(passing_tds)=3, sum(interceptions)=8.0, avg(completions)=13.75, avg(attempts)=24.0, avg(passing_yards)=138.125, avg(passing_tds)=0.375, avg(interceptions)=1.0),
 Row(player_display_name='Brett Favre', season=2006, sum(completions)=343, sum(attempts)=613, sum(passing_yards)=3885.0, sum(passing_tds)=18, sum(interceptions)=18.0, avg(completions)=21.4375, avg(attempts)=38.3125, avg(passing_yards)=242.8125, avg(passing_tds)=1.125, avg(interceptions)=1.125),
 Row(player_display_name='Drew Brees', season=2007, sum(completions)=443, sum(attempts)=655, sum(passing_yards)=4428.0, sum(passing_tds)=28, sum(interceptions)=18.0, avg(completions)=27.6875, avg(attempts)=40.9375, avg(passing_yards)=276.75, avg(passing_tds)=1.75, avg(interceptions)=1.125),
 Row(player_display_name='Bruce Gradkowski', season=2006, sum(completions)=177, sum(attempts)=328, sum(passing_yards)=1661.0, sum(passing_tds)=9, sum(interceptions)=9.0, avg(completions)=13.615384615384615, avg(attempts)=25.23076923076923, avg(passing_yards)=127.76923076923077, avg(passing_tds)=0.6923076923076923, avg(interceptions)=0.6923076923076923),
 Row(player_display_name='Matt Hasselbeck', season=2005, sum(completions)=294, sum(attempts)=450, sum(passing_yards)=3455.0, sum(passing_tds)=24, sum(interceptions)=10.0, avg(completions)=18.375, avg(attempts)=28.125, avg(passing_yards)=215.9375, avg(passing_tds)=1.5, avg(interceptions)=0.625),
 Row(player_display_name='Tony Romo', season=2005, sum(completions)=0, sum(attempts)=0, sum(passing_yards)=0.0, sum(passing_tds)=0, sum(interceptions)=0.0, avg(completions)=0.0, avg(attempts)=0.0, avg(passing_yards)=0.0, avg(passing_tds)=0.0, avg(interceptions)=0.0),
 Row(player_display_name='Patrick Ramsey', season=2005, sum(completions)=15, sum(attempts)=25, sum(passing_yards)=279.0, sum(passing_tds)=1, sum(interceptions)=1.0, avg(completions)=3.75, avg(attempts)=6.25, avg(passing_yards)=69.75, avg(passing_tds)=0.25, avg(interceptions)=0.25),
 Row(player_display_name='Tommy Maddox', season=2005, sum(completions)=34, sum(attempts)=71, sum(passing_yards)=406.0, sum(passing_tds)=2, sum(interceptions)=4.0, avg(completions)=11.333333333333334, avg(attempts)=23.666666666666668, avg(passing_yards)=135.33333333333334, avg(passing_tds)=0.6666666666666666, avg(interceptions)=1.3333333333333333),
 Row(player_display_name='Jamie Martin', season=2006, sum(completions)=16, sum(attempts)=24, sum(passing_yards)=208.0, sum(passing_tds)=1, sum(interceptions)=1.0, avg(completions)=16.0, avg(attempts)=24.0, avg(passing_yards)=208.0, avg(passing_tds)=1.0, avg(interceptions)=1.0)]

Next, we define our `completion_percentage` and `td_int_ratio` variables using the `withColumn()` method twice.
Below are the first twenty entries with these new variables added via SQL.

In [35]:
updated_QB_stats2=QB_stats2.withColumn('completion_percentage',QB_stats2['sum(completions)']/QB_stats2['sum(attempts)']) \
         .withColumn('td_int_ratio',QB_stats2['sum(passing_tds)']/QB_stats2['sum(interceptions)'])
updated_QB_stats2.take(20)

[Row(player_display_name='Jake Delhomme', season=2006, sum(completions)=263, sum(attempts)=431, sum(passing_yards)=2805.0, sum(passing_tds)=17, sum(interceptions)=11.0, avg(completions)=20.23076923076923, avg(attempts)=33.15384615384615, avg(passing_yards)=215.76923076923077, avg(passing_tds)=1.3076923076923077, avg(interceptions)=0.8461538461538461, completion_percentage=0.6102088167053364, td_int_ratio=1.5454545454545454),
 Row(player_display_name='Jake Plummer', season=2005, sum(completions)=277, sum(attempts)=456, sum(passing_yards)=3366.0, sum(passing_tds)=18, sum(interceptions)=7.0, avg(completions)=17.3125, avg(attempts)=28.5, avg(passing_yards)=210.375, avg(passing_tds)=1.125, avg(interceptions)=0.4375, completion_percentage=0.6074561403508771, td_int_ratio=2.5714285714285716),
 Row(player_display_name='Matt Schaub', season=2006, sum(completions)=18, sum(attempts)=27, sum(passing_yards)=208.0, sum(passing_tds)=1, sum(interceptions)=2.0, avg(completions)=3.6, avg(attempts)=5.4, avg(passing_yards)=41.6, avg(passing_tds)=0.2, avg(interceptions)=0.4, completion_percentage=0.6666666666666666, td_int_ratio=0.5),
 Row(player_display_name='Vince Young', season=2006, sum(completions)=184, sum(attempts)=356, sum(passing_yards)=2199.0, sum(passing_tds)=12, sum(interceptions)=13.0, avg(completions)=12.266666666666667, avg(attempts)=23.733333333333334, avg(passing_yards)=146.6, avg(passing_tds)=0.8, avg(interceptions)=0.8666666666666667, completion_percentage=0.5168539325842697, td_int_ratio=0.9230769230769231),
 Row(player_display_name='Kerry Collins', season=2007, sum(completions)=50, sum(attempts)=82, sum(passing_yards)=531.0, sum(passing_tds)=0, sum(interceptions)=0.0, avg(completions)=8.333333333333334, avg(attempts)=13.666666666666666, avg(passing_yards)=88.5, avg(passing_tds)=0.0, avg(interceptions)=0.0, completion_percentage=0.6097560975609756, td_int_ratio=None),
 Row(player_display_name='Todd Collins', season=2005, sum(completions)=0, sum(attempts)=0, sum(passing_yards)=0.0, sum(passing_tds)=0, sum(interceptions)=0.0, avg(completions)=0.0, avg(attempts)=0.0, avg(passing_yards)=0.0, avg(passing_tds)=0.0, avg(interceptions)=0.0, completion_percentage=None, td_int_ratio=None),
 Row(player_display_name='Charlie Batch', season=2006, sum(completions)=30, sum(attempts)=52, sum(passing_yards)=477.0, sum(passing_tds)=5, sum(interceptions)=0.0, avg(completions)=4.285714285714286, avg(attempts)=7.428571428571429, avg(passing_yards)=68.14285714285714, avg(passing_tds)=0.7142857142857143, avg(interceptions)=0.0, completion_percentage=0.5769230769230769, td_int_ratio=None),
 Row(player_display_name='Eli Manning', season=2006, sum(completions)=301, sum(attempts)=522, sum(passing_yards)=3244.0, sum(passing_tds)=25, sum(interceptions)=18.0, avg(completions)=18.8125, avg(attempts)=32.625, avg(passing_yards)=202.75, avg(passing_tds)=1.5625, avg(interceptions)=1.125, completion_percentage=0.5766283524904214, td_int_ratio=1.3888888888888888),
 Row(player_display_name='A.J. Feeley', season=2006, sum(completions)=26, sum(attempts)=38, sum(passing_yards)=342.0, sum(passing_tds)=3, sum(interceptions)=0.0, avg(completions)=13.0, avg(attempts)=19.0, avg(passing_yards)=171.0, avg(passing_tds)=1.5, avg(interceptions)=0.0, completion_percentage=0.6842105263157895, td_int_ratio=None),
 Row(player_display_name='Mark Brunell', season=2006, sum(completions)=162, sum(attempts)=261, sum(passing_yards)=1789.0, sum(passing_tds)=8, sum(interceptions)=4.0, avg(completions)=16.2, avg(attempts)=26.1, avg(passing_yards)=178.9, avg(passing_tds)=0.8, avg(interceptions)=0.4, completion_percentage=0.6206896551724138, td_int_ratio=2.0),
 Row(player_display_name='Shaun Hill', season=2007, sum(completions)=54, sum(attempts)=80, sum(passing_yards)=501.0, sum(passing_tds)=5, sum(interceptions)=2.0, avg(completions)=18.0, avg(attempts)=26.666666666666668, avg(passing_yards)=167.0, avg(passing_tds)=1.6666666666666667, avg(interceptions)=0.6666666666666666, completion_percentage=0.675, td_int_ratio=2.5),
 Row(player_display_name='Aaron Brooks', season=2006, sum(completions)=110, sum(attempts)=192, sum(passing_yards)=1105.0, sum(passing_tds)=3, sum(interceptions)=8.0, avg(completions)=13.75, avg(attempts)=24.0, avg(passing_yards)=138.125, avg(passing_tds)=0.375, avg(interceptions)=1.0, completion_percentage=0.5729166666666666, td_int_ratio=0.375),
 Row(player_display_name='Brett Favre', season=2006, sum(completions)=343, sum(attempts)=613, sum(passing_yards)=3885.0, sum(passing_tds)=18, sum(interceptions)=18.0, avg(completions)=21.4375, avg(attempts)=38.3125, avg(passing_yards)=242.8125, avg(passing_tds)=1.125, avg(interceptions)=1.125, completion_percentage=0.5595432300163132, td_int_ratio=1.0),
 Row(player_display_name='Drew Brees', season=2007, sum(completions)=443, sum(attempts)=655, sum(passing_yards)=4428.0, sum(passing_tds)=28, sum(interceptions)=18.0, avg(completions)=27.6875, avg(attempts)=40.9375, avg(passing_yards)=276.75, avg(passing_tds)=1.75, avg(interceptions)=1.125, completion_percentage=0.6763358778625954, td_int_ratio=1.5555555555555556),
 Row(player_display_name='Bruce Gradkowski', season=2006, sum(completions)=177, sum(attempts)=328, sum(passing_yards)=1661.0, sum(passing_tds)=9, sum(interceptions)=9.0, avg(completions)=13.615384615384615, avg(attempts)=25.23076923076923, avg(passing_yards)=127.76923076923077, avg(passing_tds)=0.6923076923076923, avg(interceptions)=0.6923076923076923, completion_percentage=0.5396341463414634, td_int_ratio=1.0),
 Row(player_display_name='Matt Hasselbeck', season=2005, sum(completions)=294, sum(attempts)=450, sum(passing_yards)=3455.0, sum(passing_tds)=24, sum(interceptions)=10.0, avg(completions)=18.375, avg(attempts)=28.125, avg(passing_yards)=215.9375, avg(passing_tds)=1.5, avg(interceptions)=0.625, completion_percentage=0.6533333333333333, td_int_ratio=2.4),
 Row(player_display_name='Tony Romo', season=2005, sum(completions)=0, sum(attempts)=0, sum(passing_yards)=0.0, sum(passing_tds)=0, sum(interceptions)=0.0, avg(completions)=0.0, avg(attempts)=0.0, avg(passing_yards)=0.0, avg(passing_tds)=0.0, avg(interceptions)=0.0, completion_percentage=None, td_int_ratio=None),
 Row(player_display_name='Patrick Ramsey', season=2005, sum(completions)=15, sum(attempts)=25, sum(passing_yards)=279.0, sum(passing_tds)=1, sum(interceptions)=1.0, avg(completions)=3.75, avg(attempts)=6.25, avg(passing_yards)=69.75, avg(passing_tds)=0.25, avg(interceptions)=0.25, completion_percentage=0.6, td_int_ratio=1.0),
 Row(player_display_name='Tommy Maddox', season=2005, sum(completions)=34, sum(attempts)=71, sum(passing_yards)=406.0, sum(passing_tds)=2, sum(interceptions)=4.0, avg(completions)=11.333333333333334, avg(attempts)=23.666666666666668, avg(passing_yards)=135.33333333333334, avg(passing_tds)=0.6666666666666666, avg(interceptions)=1.3333333333333333, completion_percentage=0.4788732394366197, td_int_ratio=0.5),
 Row(player_display_name='Jamie Martin', season=2006, sum(completions)=16, sum(attempts)=24, sum(passing_yards)=208.0, sum(passing_tds)=1, sum(interceptions)=1.0, avg(completions)=16.0, avg(attempts)=24.0, avg(passing_yards)=208.0, avg(passing_tds)=1.0, avg(interceptions)=1.0, completion_percentage=0.6666666666666666, td_int_ratio=1.0)]

Again, using SQL, here are the first twenty entries for the quarterback players who got a total of at least 50 attempts.

In [36]:
updated_QB_stats2.filter(updated_QB_stats2['sum(attempts)'] >= 50).take(20)

[Row(player_display_name='Jake Delhomme', season=2006, sum(completions)=263, sum(attempts)=431, sum(passing_yards)=2805.0, sum(passing_tds)=17, sum(interceptions)=11.0, avg(completions)=20.23076923076923, avg(attempts)=33.15384615384615, avg(passing_yards)=215.76923076923077, avg(passing_tds)=1.3076923076923077, avg(interceptions)=0.8461538461538461, completion_percentage=0.6102088167053364, td_int_ratio=1.5454545454545454),
 Row(player_display_name='Jake Plummer', season=2005, sum(completions)=277, sum(attempts)=456, sum(passing_yards)=3366.0, sum(passing_tds)=18, sum(interceptions)=7.0, avg(completions)=17.3125, avg(attempts)=28.5, avg(passing_yards)=210.375, avg(passing_tds)=1.125, avg(interceptions)=0.4375, completion_percentage=0.6074561403508771, td_int_ratio=2.5714285714285716),
 Row(player_display_name='Vince Young', season=2006, sum(completions)=184, sum(attempts)=356, sum(passing_yards)=2199.0, sum(passing_tds)=12, sum(interceptions)=13.0, avg(completions)=12.266666666666667, avg(attempts)=23.733333333333334, avg(passing_yards)=146.6, avg(passing_tds)=0.8, avg(interceptions)=0.8666666666666667, completion_percentage=0.5168539325842697, td_int_ratio=0.9230769230769231),
 Row(player_display_name='Kerry Collins', season=2007, sum(completions)=50, sum(attempts)=82, sum(passing_yards)=531.0, sum(passing_tds)=0, sum(interceptions)=0.0, avg(completions)=8.333333333333334, avg(attempts)=13.666666666666666, avg(passing_yards)=88.5, avg(passing_tds)=0.0, avg(interceptions)=0.0, completion_percentage=0.6097560975609756, td_int_ratio=None),
 Row(player_display_name='Charlie Batch', season=2006, sum(completions)=30, sum(attempts)=52, sum(passing_yards)=477.0, sum(passing_tds)=5, sum(interceptions)=0.0, avg(completions)=4.285714285714286, avg(attempts)=7.428571428571429, avg(passing_yards)=68.14285714285714, avg(passing_tds)=0.7142857142857143, avg(interceptions)=0.0, completion_percentage=0.5769230769230769, td_int_ratio=None),
 Row(player_display_name='Eli Manning', season=2006, sum(completions)=301, sum(attempts)=522, sum(passing_yards)=3244.0, sum(passing_tds)=25, sum(interceptions)=18.0, avg(completions)=18.8125, avg(attempts)=32.625, avg(passing_yards)=202.75, avg(passing_tds)=1.5625, avg(interceptions)=1.125, completion_percentage=0.5766283524904214, td_int_ratio=1.3888888888888888),
 Row(player_display_name='Mark Brunell', season=2006, sum(completions)=162, sum(attempts)=261, sum(passing_yards)=1789.0, sum(passing_tds)=8, sum(interceptions)=4.0, avg(completions)=16.2, avg(attempts)=26.1, avg(passing_yards)=178.9, avg(passing_tds)=0.8, avg(interceptions)=0.4, completion_percentage=0.6206896551724138, td_int_ratio=2.0),
 Row(player_display_name='Shaun Hill', season=2007, sum(completions)=54, sum(attempts)=80, sum(passing_yards)=501.0, sum(passing_tds)=5, sum(interceptions)=2.0, avg(completions)=18.0, avg(attempts)=26.666666666666668, avg(passing_yards)=167.0, avg(passing_tds)=1.6666666666666667, avg(interceptions)=0.6666666666666666, completion_percentage=0.675, td_int_ratio=2.5),
 Row(player_display_name='Aaron Brooks', season=2006, sum(completions)=110, sum(attempts)=192, sum(passing_yards)=1105.0, sum(passing_tds)=3, sum(interceptions)=8.0, avg(completions)=13.75, avg(attempts)=24.0, avg(passing_yards)=138.125, avg(passing_tds)=0.375, avg(interceptions)=1.0, completion_percentage=0.5729166666666666, td_int_ratio=0.375),
 Row(player_display_name='Brett Favre', season=2006, sum(completions)=343, sum(attempts)=613, sum(passing_yards)=3885.0, sum(passing_tds)=18, sum(interceptions)=18.0, avg(completions)=21.4375, avg(attempts)=38.3125, avg(passing_yards)=242.8125, avg(passing_tds)=1.125, avg(interceptions)=1.125, completion_percentage=0.5595432300163132, td_int_ratio=1.0),
 Row(player_display_name='Drew Brees', season=2007, sum(completions)=443, sum(attempts)=655, sum(passing_yards)=4428.0, sum(passing_tds)=28, sum(interceptions)=18.0, avg(completions)=27.6875, avg(attempts)=40.9375, avg(passing_yards)=276.75, avg(passing_tds)=1.75, avg(interceptions)=1.125, completion_percentage=0.6763358778625954, td_int_ratio=1.5555555555555556),
 Row(player_display_name='Bruce Gradkowski', season=2006, sum(completions)=177, sum(attempts)=328, sum(passing_yards)=1661.0, sum(passing_tds)=9, sum(interceptions)=9.0, avg(completions)=13.615384615384615, avg(attempts)=25.23076923076923, avg(passing_yards)=127.76923076923077, avg(passing_tds)=0.6923076923076923, avg(interceptions)=0.6923076923076923, completion_percentage=0.5396341463414634, td_int_ratio=1.0),
 Row(player_display_name='Matt Hasselbeck', season=2005, sum(completions)=294, sum(attempts)=450, sum(passing_yards)=3455.0, sum(passing_tds)=24, sum(interceptions)=10.0, avg(completions)=18.375, avg(attempts)=28.125, avg(passing_yards)=215.9375, avg(passing_tds)=1.5, avg(interceptions)=0.625, completion_percentage=0.6533333333333333, td_int_ratio=2.4),
 Row(player_display_name='Tommy Maddox', season=2005, sum(completions)=34, sum(attempts)=71, sum(passing_yards)=406.0, sum(passing_tds)=2, sum(interceptions)=4.0, avg(completions)=11.333333333333334, avg(attempts)=23.666666666666668, avg(passing_yards)=135.33333333333334, avg(passing_tds)=0.6666666666666666, avg(interceptions)=1.3333333333333333, completion_percentage=0.4788732394366197, td_int_ratio=0.5),
 Row(player_display_name='Jake Delhomme', season=2007, sum(completions)=55, sum(attempts)=86, sum(passing_yards)=617.0, sum(passing_tds)=8, sum(interceptions)=1.0, avg(completions)=18.333333333333332, avg(attempts)=28.666666666666668, avg(passing_yards)=205.66666666666666, avg(passing_tds)=2.6666666666666665, avg(interceptions)=0.3333333333333333, completion_percentage=0.6395348837209303, td_int_ratio=8.0),
 Row(player_display_name='Mark Brunell', season=2005, sum(completions)=262, sum(attempts)=454, sum(passing_yards)=3050.0, sum(passing_tds)=23, sum(interceptions)=10.0, avg(completions)=16.375, avg(attempts)=28.375, avg(passing_yards)=190.625, avg(passing_tds)=1.4375, avg(interceptions)=0.625, completion_percentage=0.5770925110132159, td_int_ratio=2.3),
 Row(player_display_name='Marc Bulger', season=2007, sum(completions)=221, sum(attempts)=378, sum(passing_yards)=2392.0, sum(passing_tds)=11, sum(interceptions)=15.0, avg(completions)=18.416666666666668, avg(attempts)=31.5, avg(passing_yards)=199.33333333333334, avg(passing_tds)=0.9166666666666666, avg(interceptions)=1.25, completion_percentage=0.5846560846560847, td_int_ratio=0.7333333333333333),
 Row(player_display_name='David Garrard', season=2007, sum(completions)=208, sum(attempts)=325, sum(passing_yards)=2509.0, sum(passing_tds)=18, sum(interceptions)=3.0, avg(completions)=17.333333333333332, avg(attempts)=27.083333333333332, avg(passing_yards)=209.08333333333334, avg(passing_tds)=1.5, avg(interceptions)=0.25, completion_percentage=0.64, td_int_ratio=6.0),
 Row(player_display_name='Kurt Warner', season=2005, sum(completions)=242, sum(attempts)=375, sum(passing_yards)=2713.0, sum(passing_tds)=11, sum(interceptions)=9.0, avg(completions)=24.2, avg(attempts)=37.5, avg(passing_yards)=271.3, avg(passing_tds)=1.1, avg(interceptions)=0.9, completion_percentage=0.6453333333333333, td_int_ratio=1.2222222222222223),
 Row(player_display_name='Kelly Holcomb', season=2007, sum(completions)=42, sum(attempts)=83, sum(passing_yards)=511.0, sum(passing_tds)=2, sum(interceptions)=1.0, avg(completions)=14.0, avg(attempts)=27.666666666666668, avg(passing_yards)=170.33333333333334, avg(passing_tds)=0.6666666666666666, avg(interceptions)=0.3333333333333333, completion_percentage=0.5060240963855421, td_int_ratio=2.0)]

Here are the top 40 completion percentages. It appears to be nearly the same as before, but with a different ordering due to the `td-int-ratio` being computed differently when using SQL.

In [37]:
updated_QB_stats2.sort('completion_percentage',ascending=False).take(40)

[Row(player_display_name='Anthony Wright', season=2006, sum(completions)=3, sum(attempts)=3, sum(passing_yards)=31.0, sum(passing_tds)=0, sum(interceptions)=0.0, avg(completions)=1.5, avg(attempts)=1.5, avg(passing_yards)=15.5, avg(passing_tds)=0.0, avg(interceptions)=0.0, completion_percentage=1.0, td_int_ratio=None),
 Row(player_display_name='Matt Gutierrez', season=2007, sum(completions)=1, sum(attempts)=1, sum(passing_yards)=15.0, sum(passing_tds)=0, sum(interceptions)=0.0, avg(completions)=0.25, avg(attempts)=0.25, avg(passing_yards)=3.75, avg(passing_tds)=0.0, avg(interceptions)=0.0, completion_percentage=1.0, td_int_ratio=None),
 Row(player_display_name='Matt Gutierrez', season=2009, sum(completions)=1, sum(attempts)=1, sum(passing_yards)=3.0, sum(passing_tds)=0, sum(interceptions)=0.0, avg(completions)=1.0, avg(attempts)=1.0, avg(passing_yards)=3.0, avg(passing_tds)=0.0, avg(interceptions)=0.0, completion_percentage=1.0, td_int_ratio=None),
 Row(player_display_name='Brad Smith', season=2009, sum(completions)=1, sum(attempts)=1, sum(passing_yards)=27.0, sum(passing_tds)=0, sum(interceptions)=0.0, avg(completions)=0.09090909090909091, avg(attempts)=0.09090909090909091, avg(passing_yards)=2.4545454545454546, avg(passing_tds)=0.0, avg(interceptions)=0.0, completion_percentage=1.0, td_int_ratio=None),
 Row(player_display_name='Billy Volek', season=2010, sum(completions)=1, sum(attempts)=1, sum(passing_yards)=8.0, sum(passing_tds)=0, sum(interceptions)=0.0, avg(completions)=0.3333333333333333, avg(attempts)=0.3333333333333333, avg(passing_yards)=2.6666666666666665, avg(passing_tds)=0.0, avg(interceptions)=0.0, completion_percentage=1.0, td_int_ratio=None),
 Row(player_display_name='Jordan Palmer', season=2010, sum(completions)=3, sum(attempts)=3, sum(passing_yards)=18.0, sum(passing_tds)=0, sum(interceptions)=0.0, avg(completions)=3.0, avg(attempts)=3.0, avg(passing_yards)=18.0, avg(passing_tds)=0.0, avg(interceptions)=0.0, completion_percentage=1.0, td_int_ratio=None),
 Row(player_display_name='Dennis Dixon', season=2008, sum(completions)=1, sum(attempts)=1, sum(passing_yards)=3.0, sum(passing_tds)=0, sum(interceptions)=0.0, avg(completions)=1.0, avg(attempts)=1.0, avg(passing_yards)=3.0, avg(passing_tds)=0.0, avg(interceptions)=0.0, completion_percentage=1.0, td_int_ratio=None),
 Row(player_display_name='Colt McCoy', season=2013, sum(completions)=1, sum(attempts)=1, sum(passing_yards)=13.0, sum(passing_tds)=0, sum(interceptions)=0.0, avg(completions)=0.3333333333333333, avg(attempts)=0.3333333333333333, avg(passing_yards)=4.333333333333333, avg(passing_tds)=0.0, avg(interceptions)=0.0, completion_percentage=1.0, td_int_ratio=None),
 Row(player_display_name='Tyrod Taylor', season=2011, sum(completions)=1, sum(attempts)=1, sum(passing_yards)=18.0, sum(passing_tds)=0, sum(interceptions)=0.0, avg(completions)=0.5, avg(attempts)=0.5, avg(passing_yards)=9.0, avg(passing_tds)=0.0, avg(interceptions)=0.0, completion_percentage=1.0, td_int_ratio=None),
 Row(player_display_name='Trent Edwards', season=2012, sum(completions)=2, sum(attempts)=2, sum(passing_yards)=14.0, sum(passing_tds)=0, sum(interceptions)=0.0, avg(completions)=2.0, avg(attempts)=2.0, avg(passing_yards)=14.0, avg(passing_tds)=0.0, avg(interceptions)=0.0, completion_percentage=1.0, td_int_ratio=None),
 Row(player_display_name='Chase Daniel', season=2012, sum(completions)=1, sum(attempts)=1, sum(passing_yards)=10.0, sum(passing_tds)=0, sum(interceptions)=0.0, avg(completions)=1.0, avg(attempts)=1.0, avg(passing_yards)=10.0, avg(passing_tds)=0.0, avg(interceptions)=0.0, completion_percentage=1.0, td_int_ratio=None),
 Row(player_display_name='Derek Anderson', season=2012, sum(completions)=4, sum(attempts)=4, sum(passing_yards)=58.0, sum(passing_tds)=0, sum(interceptions)=0.0, avg(completions)=2.0, avg(attempts)=2.0, avg(passing_yards)=29.0, avg(passing_tds)=0.0, avg(interceptions)=0.0, completion_percentage=1.0, td_int_ratio=None),
 Row(player_display_name='Brian Hoyer', season=2011, sum(completions)=1, sum(attempts)=1, sum(passing_yards)=22.0, sum(passing_tds)=0, sum(interceptions)=0.0, avg(completions)=0.5, avg(attempts)=0.5, avg(passing_yards)=11.0, avg(passing_tds)=0.0, avg(interceptions)=0.0, completion_percentage=1.0, td_int_ratio=None),
 Row(player_display_name='Tarvaris Jackson', season=2014, sum(completions)=1, sum(attempts)=1, sum(passing_yards)=0.0, sum(passing_tds)=0, sum(interceptions)=0.0, avg(completions)=1.0, avg(attempts)=1.0, avg(passing_yards)=0.0, avg(passing_tds)=0.0, avg(interceptions)=0.0, completion_percentage=1.0, td_int_ratio=None),
 Row(player_display_name='Scott Tolzien', season=2015, sum(completions)=1, sum(attempts)=1, sum(passing_yards)=4.0, sum(passing_tds)=0, sum(interceptions)=0.0, avg(completions)=0.5, avg(attempts)=0.5, avg(passing_yards)=2.0, avg(passing_tds)=0.0, avg(interceptions)=0.0, completion_percentage=1.0, td_int_ratio=None),
 Row(player_display_name='Matt Moore', season=2015, sum(completions)=1, sum(attempts)=1, sum(passing_yards)=14.0, sum(passing_tds)=0, sum(interceptions)=0.0, avg(completions)=1.0, avg(attempts)=1.0, avg(passing_yards)=14.0, avg(passing_tds)=0.0, avg(interceptions)=0.0, completion_percentage=1.0, td_int_ratio=None),
 Row(player_display_name='Chase Daniel', season=2015, sum(completions)=2, sum(attempts)=2, sum(passing_yards)=4.0, sum(passing_tds)=0, sum(interceptions)=0.0, avg(completions)=1.0, avg(attempts)=1.0, avg(passing_yards)=2.0, avg(passing_tds)=0.0, avg(interceptions)=0.0, completion_percentage=1.0, td_int_ratio=None),
 Row(player_display_name='Ryan Nassib', season=2015, sum(completions)=5, sum(attempts)=5, sum(passing_yards)=68.0, sum(passing_tds)=1, sum(interceptions)=0.0, avg(completions)=5.0, avg(attempts)=5.0, avg(passing_yards)=68.0, avg(passing_tds)=1.0, avg(interceptions)=0.0, completion_percentage=1.0, td_int_ratio=None),
 Row(player_display_name='Chase Daniel', season=2016, sum(completions)=1, sum(attempts)=1, sum(passing_yards)=16.0, sum(passing_tds)=0, sum(interceptions)=0.0, avg(completions)=1.0, avg(attempts)=1.0, avg(passing_yards)=16.0, avg(passing_tds)=0.0, avg(interceptions)=0.0, completion_percentage=1.0, td_int_ratio=None),
 Row(player_display_name='Alex Tanney', season=2019, sum(completions)=1, sum(attempts)=1, sum(passing_yards)=1.0, sum(passing_tds)=0, sum(interceptions)=0.0, avg(completions)=1.0, avg(attempts)=1.0, avg(passing_yards)=1.0, avg(passing_tds)=0.0, avg(interceptions)=0.0, completion_percentage=1.0, td_int_ratio=None),
 Row(player_display_name='Taylor Heinicke', season=2017, sum(completions)=1, sum(attempts)=1, sum(passing_yards)=10.0, sum(passing_tds)=0, sum(interceptions)=0.0, avg(completions)=1.0, avg(attempts)=1.0, avg(passing_yards)=10.0, avg(passing_tds)=0.0, avg(interceptions)=0.0, completion_percentage=1.0, td_int_ratio=None),
 Row(player_display_name='Easton Stick', season=2020, sum(completions)=1, sum(attempts)=1, sum(passing_yards)=4.0, sum(passing_tds)=0, sum(interceptions)=0.0, avg(completions)=1.0, avg(attempts)=1.0, avg(passing_yards)=4.0, avg(passing_tds)=0.0, avg(interceptions)=0.0, completion_percentage=1.0, td_int_ratio=None),
 Row(player_display_name='C.J. Beathard', season=2021, sum(completions)=2, sum(attempts)=2, sum(passing_yards)=33.0, sum(passing_tds)=0, sum(interceptions)=0.0, avg(completions)=1.0, avg(attempts)=1.0, avg(passing_yards)=16.5, avg(passing_tds)=0.0, avg(interceptions)=0.0, completion_percentage=1.0, td_int_ratio=None),
 Row(player_display_name='AJ McCarron', season=2020, sum(completions)=1, sum(attempts)=1, sum(passing_yards)=20.0, sum(passing_tds)=0, sum(interceptions)=0.0, avg(completions)=0.5, avg(attempts)=0.5, avg(passing_yards)=10.0, avg(passing_tds)=0.0, avg(interceptions)=0.0, completion_percentage=1.0, td_int_ratio=None),
 Row(player_display_name='Brandon Allen', season=2022, sum(completions)=3, sum(attempts)=3, sum(passing_yards)=22.0, sum(passing_tds)=0, sum(interceptions)=0.0, avg(completions)=3.0, avg(attempts)=3.0, avg(passing_yards)=22.0, avg(passing_tds)=0.0, avg(interceptions)=0.0, completion_percentage=1.0, td_int_ratio=None),
 Row(player_display_name='Sean Clifford', season=2023, sum(completions)=1, sum(attempts)=1, sum(passing_yards)=37.0, sum(passing_tds)=0, sum(interceptions)=0.0, avg(completions)=0.5, avg(attempts)=0.5, avg(passing_yards)=18.5, avg(passing_tds)=0.0, avg(interceptions)=0.0, completion_percentage=1.0, td_int_ratio=None),
 Row(player_display_name='Mike Glennon', season=2016, sum(completions)=10, sum(attempts)=11, sum(passing_yards)=75.0, sum(passing_tds)=1, sum(interceptions)=0.0, avg(completions)=10.0, avg(attempts)=11.0, avg(passing_yards)=75.0, avg(passing_tds)=1.0, avg(interceptions)=0.0, completion_percentage=0.9090909090909091, td_int_ratio=None),
 Row(player_display_name='Kyle Orton', season=2012, sum(completions)=9, sum(attempts)=10, sum(passing_yards)=89.0, sum(passing_tds)=1, sum(interceptions)=0.0, avg(completions)=9.0, avg(attempts)=10.0, avg(passing_yards)=89.0, avg(passing_tds)=1.0, avg(interceptions)=0.0, completion_percentage=0.9, td_int_ratio=None),
 Row(player_display_name='Jeff Blake', season=2005, sum(completions)=8, sum(attempts)=9, sum(passing_yards)=55.0, sum(passing_tds)=1, sum(interceptions)=0.0, avg(completions)=4.0, avg(attempts)=4.5, avg(passing_yards)=27.5, avg(passing_tds)=0.5, avg(interceptions)=0.0, completion_percentage=0.8888888888888888, td_int_ratio=None),
 Row(player_display_name='Josh Johnson', season=2010, sum(completions)=14, sum(attempts)=16, sum(passing_yards)=111.0, sum(passing_tds)=0, sum(interceptions)=0.0, avg(completions)=1.75, avg(attempts)=2.0, avg(passing_yards)=13.875, avg(passing_tds)=0.0, avg(interceptions)=0.0, completion_percentage=0.875, td_int_ratio=None),
 Row(player_display_name='Quinn Gray', season=2008, sum(completions)=7, sum(attempts)=8, sum(passing_yards)=76.0, sum(passing_tds)=1, sum(interceptions)=0.0, avg(completions)=7.0, avg(attempts)=8.0, avg(passing_yards)=76.0, avg(passing_tds)=1.0, avg(interceptions)=0.0, completion_percentage=0.875, td_int_ratio=None),
 Row(player_display_name='Sean Mannion', season=2015, sum(completions)=6, sum(attempts)=7, sum(passing_yards)=31.0, sum(passing_tds)=0, sum(interceptions)=0.0, avg(completions)=6.0, avg(attempts)=7.0, avg(passing_yards)=31.0, avg(passing_tds)=0.0, avg(interceptions)=0.0, completion_percentage=0.8571428571428571, td_int_ratio=None),
 Row(player_display_name='Nick Mullens', season=2022, sum(completions)=21, sum(attempts)=25, sum(passing_yards)=224.0, sum(passing_tds)=1, sum(interceptions)=1.0, avg(completions)=5.25, avg(attempts)=6.25, avg(passing_yards)=56.0, avg(passing_tds)=0.25, avg(interceptions)=0.25, completion_percentage=0.84, td_int_ratio=1.0),
 Row(player_display_name='Kellen Clemens', season=2015, sum(completions)=5, sum(attempts)=6, sum(passing_yards)=63.0, sum(passing_tds)=1, sum(interceptions)=0.0, avg(completions)=2.5, avg(attempts)=3.0, avg(passing_yards)=31.5, avg(passing_tds)=0.5, avg(interceptions)=0.0, completion_percentage=0.8333333333333334, td_int_ratio=None),
 Row(player_display_name='Brian Hoyer', season=2022, sum(completions)=5, sum(attempts)=6, sum(passing_yards)=37.0, sum(passing_tds)=0, sum(interceptions)=0.0, avg(completions)=5.0, avg(attempts)=6.0, avg(passing_yards)=37.0, avg(passing_tds)=0.0, avg(interceptions)=0.0, completion_percentage=0.8333333333333334, td_int_ratio=None),
 Row(player_display_name='Mike White', season=2023, sum(completions)=5, sum(attempts)=6, sum(passing_yards)=74.0, sum(passing_tds)=1, sum(interceptions)=1.0, avg(completions)=0.8333333333333334, avg(attempts)=1.0, avg(passing_yards)=12.333333333333334, avg(passing_tds)=0.16666666666666666, avg(interceptions)=0.16666666666666666, completion_percentage=0.8333333333333334, td_int_ratio=1.0),
 Row(player_display_name='Nate Sudfeld', season=2017, sum(completions)=19, sum(attempts)=23, sum(passing_yards)=134.0, sum(passing_tds)=0, sum(interceptions)=0.0, avg(completions)=19.0, avg(attempts)=23.0, avg(passing_yards)=134.0, avg(passing_tds)=0.0, avg(interceptions)=0.0, completion_percentage=0.8260869565217391, td_int_ratio=None),
 Row(player_display_name='Landry Jones', season=2017, sum(completions)=23, sum(attempts)=28, sum(passing_yards)=239.0, sum(passing_tds)=1, sum(interceptions)=1.0, avg(completions)=7.666666666666667, avg(attempts)=9.333333333333334, avg(passing_yards)=79.66666666666667, avg(passing_tds)=0.3333333333333333, avg(interceptions)=0.3333333333333333, completion_percentage=0.8214285714285714, td_int_ratio=1.0),
 Row(player_display_name='Luke McCown', season=2015, sum(completions)=32, sum(attempts)=39, sum(passing_yards)=335.0, sum(passing_tds)=0, sum(interceptions)=1.0, avg(completions)=16.0, avg(attempts)=19.5, avg(passing_yards)=167.5, avg(passing_tds)=0.0, avg(interceptions)=0.5, completion_percentage=0.8205128205128205, td_int_ratio=0.0),
 Row(player_display_name='Brian Hoyer', season=2021, sum(completions)=9, sum(attempts)=11, sum(passing_yards)=227.0, sum(passing_tds)=1, sum(interceptions)=0.0, avg(completions)=1.8, avg(attempts)=2.2, avg(passing_yards)=45.4, avg(passing_tds)=0.2, avg(interceptions)=0.0, completion_percentage=0.8181818181818182, td_int_ratio=None)]

Lastly, here are the top 40 touchdown-to-interception ratios. As mentioned before, unlike `pandas`, which treated 0/0 as `NaN` and a positive number divided by zero as `inf`, SQL lumped these two quantity types into one category, simple called `None`.

In [38]:
updated_QB_stats2.sort('td_int_ratio',ascending=False).take(40)

[Row(player_display_name='Tom Brady', season=2016, sum(completions)=291, sum(attempts)=432, sum(passing_yards)=3554.0, sum(passing_tds)=28, sum(interceptions)=2.0, avg(completions)=24.25, avg(attempts)=36.0, avg(passing_yards)=296.1666666666667, avg(passing_tds)=2.3333333333333335, avg(interceptions)=0.16666666666666666, completion_percentage=0.6736111111111112, td_int_ratio=14.0),
 Row(player_display_name='Nick Foles', season=2013, sum(completions)=203, sum(attempts)=317, sum(passing_yards)=2891.0, sum(passing_tds)=27, sum(interceptions)=2.0, avg(completions)=15.615384615384615, avg(attempts)=24.384615384615383, avg(passing_yards)=222.3846153846154, avg(passing_tds)=2.076923076923077, avg(interceptions)=0.15384615384615385, completion_percentage=0.6403785488958991, td_int_ratio=13.5),
 Row(player_display_name='Josh McCown', season=2013, sum(completions)=149, sum(attempts)=224, sum(passing_yards)=1829.0, sum(passing_tds)=13, sum(interceptions)=1.0, avg(completions)=18.625, avg(attempts)=28.0, avg(passing_yards)=228.625, avg(passing_tds)=1.625, avg(interceptions)=0.125, completion_percentage=0.6651785714285714, td_int_ratio=13.0),
 Row(player_display_name='Aaron Rodgers', season=2018, sum(completions)=372, sum(attempts)=597, sum(passing_yards)=4442.0, sum(passing_tds)=25, sum(interceptions)=2.0, avg(completions)=23.25, avg(attempts)=37.3125, avg(passing_yards)=277.625, avg(passing_tds)=1.5625, avg(interceptions)=0.125, completion_percentage=0.6231155778894473, td_int_ratio=12.5),
 Row(player_display_name='Damon Huard', season=2006, sum(completions)=148, sum(attempts)=244, sum(passing_yards)=1878.0, sum(passing_tds)=11, sum(interceptions)=1.0, avg(completions)=14.8, avg(attempts)=24.4, avg(passing_yards)=187.8, avg(passing_tds)=1.1, avg(interceptions)=0.1, completion_percentage=0.6065573770491803, td_int_ratio=11.0),
 Row(player_display_name='Aaron Rodgers', season=2020, sum(completions)=372, sum(attempts)=526, sum(passing_yards)=4299.0, sum(passing_tds)=48, sum(interceptions)=5.0, avg(completions)=23.25, avg(attempts)=32.875, avg(passing_yards)=268.6875, avg(passing_tds)=3.0, avg(interceptions)=0.3125, completion_percentage=0.7072243346007605, td_int_ratio=9.6),
 Row(player_display_name='Aaron Rodgers', season=2021, sum(completions)=366, sum(attempts)=531, sum(passing_yards)=4115.0, sum(passing_tds)=37, sum(interceptions)=4.0, avg(completions)=22.875, avg(attempts)=33.1875, avg(passing_yards)=257.1875, avg(passing_tds)=2.3125, avg(interceptions)=0.25, completion_percentage=0.6892655367231638, td_int_ratio=9.25),
 Row(player_display_name='Tom Brady', season=2010, sum(completions)=324, sum(attempts)=492, sum(passing_yards)=3900.0, sum(passing_tds)=36, sum(interceptions)=4.0, avg(completions)=20.25, avg(attempts)=30.75, avg(passing_yards)=243.75, avg(passing_tds)=2.25, avg(interceptions)=0.25, completion_percentage=0.6585365853658537, td_int_ratio=9.0),
 Row(player_display_name='Jake Delhomme', season=2007, sum(completions)=55, sum(attempts)=86, sum(passing_yards)=617.0, sum(passing_tds)=8, sum(interceptions)=1.0, avg(completions)=18.333333333333332, avg(attempts)=28.666666666666668, avg(passing_yards)=205.66666666666666, avg(passing_tds)=2.6666666666666665, avg(interceptions)=0.3333333333333333, completion_percentage=0.6395348837209303, td_int_ratio=8.0),
 Row(player_display_name='Aaron Rodgers', season=2014, sum(completions)=341, sum(attempts)=520, sum(passing_yards)=4381.0, sum(passing_tds)=38, sum(interceptions)=5.0, avg(completions)=21.3125, avg(attempts)=32.5, avg(passing_yards)=273.8125, avg(passing_tds)=2.375, avg(interceptions)=0.3125, completion_percentage=0.6557692307692308, td_int_ratio=7.6),
 Row(player_display_name='Aaron Rodgers', season=2011, sum(completions)=342, sum(attempts)=501, sum(passing_yards)=4636.0, sum(passing_tds)=45, sum(interceptions)=6.0, avg(completions)=22.8, avg(attempts)=33.4, avg(passing_yards)=309.06666666666666, avg(passing_tds)=3.0, avg(interceptions)=0.4, completion_percentage=0.6826347305389222, td_int_ratio=7.5),
 Row(player_display_name='Drew Brees', season=2019, sum(completions)=281, sum(attempts)=378, sum(passing_yards)=2979.0, sum(passing_tds)=27, sum(interceptions)=4.0, avg(completions)=25.545454545454547, avg(attempts)=34.36363636363637, avg(passing_yards)=270.8181818181818, avg(passing_tds)=2.4545454545454546, avg(interceptions)=0.36363636363636365, completion_percentage=0.7433862433862434, td_int_ratio=6.75),
 Row(player_display_name='Aaron Rodgers', season=2019, sum(completions)=353, sum(attempts)=569, sum(passing_yards)=4002.0, sum(passing_tds)=26, sum(interceptions)=4.0, avg(completions)=22.0625, avg(attempts)=35.5625, avg(passing_yards)=250.125, avg(passing_tds)=1.625, avg(interceptions)=0.25, completion_percentage=0.6203866432337434, td_int_ratio=6.5),
 Row(player_display_name='Drew Brees', season=2018, sum(completions)=364, sum(attempts)=489, sum(passing_yards)=3992.0, sum(passing_tds)=32, sum(interceptions)=5.0, avg(completions)=24.266666666666666, avg(attempts)=32.6, avg(passing_yards)=266.1333333333333, avg(passing_tds)=2.1333333333333333, avg(interceptions)=0.3333333333333333, completion_percentage=0.7443762781186094, td_int_ratio=6.4),
 Row(player_display_name='Patrick Mahomes', season=2020, sum(completions)=390, sum(attempts)=588, sum(passing_yards)=4740.0, sum(passing_tds)=38, sum(interceptions)=6.0, avg(completions)=26.0, avg(attempts)=39.2, avg(passing_yards)=316.0, avg(passing_tds)=2.533333333333333, avg(interceptions)=0.4, completion_percentage=0.6632653061224489, td_int_ratio=6.333333333333333),
 Row(player_display_name='Tom Brady', season=2007, sum(completions)=398, sum(attempts)=578, sum(passing_yards)=4806.0, sum(passing_tds)=50, sum(interceptions)=8.0, avg(completions)=24.875, avg(attempts)=36.125, avg(passing_yards)=300.375, avg(passing_tds)=3.125, avg(interceptions)=0.5, completion_percentage=0.6885813148788927, td_int_ratio=6.25),
 Row(player_display_name='Russell Wilson', season=2019, sum(completions)=341, sum(attempts)=516, sum(passing_yards)=4110.0, sum(passing_tds)=31, sum(interceptions)=5.0, avg(completions)=21.3125, avg(attempts)=32.25, avg(passing_yards)=256.875, avg(passing_tds)=1.9375, avg(interceptions)=0.3125, completion_percentage=0.6608527131782945, td_int_ratio=6.2),
 Row(player_display_name='Matthew Stafford', season=2010, sum(completions)=57, sum(attempts)=96, sum(passing_yards)=535.0, sum(passing_tds)=6, sum(interceptions)=1.0, avg(completions)=14.25, avg(attempts)=24.0, avg(passing_yards)=133.75, avg(passing_tds)=1.5, avg(interceptions)=0.25, completion_percentage=0.59375, td_int_ratio=6.0),
 Row(player_display_name='David Garrard', season=2007, sum(completions)=208, sum(attempts)=325, sum(passing_yards)=2509.0, sum(passing_tds)=18, sum(interceptions)=3.0, avg(completions)=17.333333333333332, avg(attempts)=27.083333333333332, avg(passing_yards)=209.08333333333334, avg(passing_tds)=1.5, avg(interceptions)=0.25, completion_percentage=0.64, td_int_ratio=6.0),
 Row(player_display_name='Lamar Jackson', season=2019, sum(completions)=265, sum(attempts)=401, sum(passing_yards)=3127.0, sum(passing_tds)=36, sum(interceptions)=6.0, avg(completions)=17.666666666666668, avg(attempts)=26.733333333333334, avg(passing_yards)=208.46666666666667, avg(passing_tds)=2.4, avg(interceptions)=0.4, completion_percentage=0.6608478802992519, td_int_ratio=6.0),
 Row(player_display_name='Dak Prescott', season=2016, sum(completions)=311, sum(attempts)=459, sum(passing_yards)=3667.0, sum(passing_tds)=23, sum(interceptions)=4.0, avg(completions)=19.4375, avg(attempts)=28.6875, avg(passing_yards)=229.1875, avg(passing_tds)=1.4375, avg(interceptions)=0.25, completion_percentage=0.6775599128540305, td_int_ratio=5.75),
 Row(player_display_name='Aaron Rodgers', season=2016, sum(completions)=401, sum(attempts)=610, sum(passing_yards)=4428.0, sum(passing_tds)=40, sum(interceptions)=7.0, avg(completions)=25.0625, avg(attempts)=38.125, avg(passing_yards)=276.75, avg(passing_tds)=2.5, avg(interceptions)=0.4375, completion_percentage=0.6573770491803279, td_int_ratio=5.714285714285714),
 Row(player_display_name='Peyton Manning', season=2013, sum(completions)=450, sum(attempts)=659, sum(passing_yards)=5477.0, sum(passing_tds)=55, sum(interceptions)=10.0, avg(completions)=28.125, avg(attempts)=41.1875, avg(passing_yards)=342.3125, avg(passing_tds)=3.4375, avg(interceptions)=0.625, completion_percentage=0.6828528072837633, td_int_ratio=5.5),
 Row(player_display_name='Matt Ryan', season=2016, sum(completions)=373, sum(attempts)=534, sum(passing_yards)=4944.0, sum(passing_tds)=38, sum(interceptions)=7.0, avg(completions)=23.3125, avg(attempts)=33.375, avg(passing_yards)=309.0, avg(passing_tds)=2.375, avg(interceptions)=0.4375, completion_percentage=0.6985018726591761, td_int_ratio=5.428571428571429),
 Row(player_display_name='Alex Smith', season=2017, sum(completions)=341, sum(attempts)=505, sum(passing_yards)=4042.0, sum(passing_tds)=26, sum(interceptions)=5.0, avg(completions)=22.733333333333334, avg(attempts)=33.666666666666664, avg(passing_yards)=269.46666666666664, avg(passing_tds)=1.7333333333333334, avg(interceptions)=0.3333333333333333, completion_percentage=0.6752475247524753, td_int_ratio=5.2),
 Row(player_display_name='Patrick Mahomes', season=2019, sum(completions)=319, sum(attempts)=484, sum(passing_yards)=4031.0, sum(passing_tds)=26, sum(interceptions)=5.0, avg(completions)=22.785714285714285, avg(attempts)=34.57142857142857, avg(passing_yards)=287.92857142857144, avg(passing_tds)=1.8571428571428572, avg(interceptions)=0.35714285714285715, completion_percentage=0.6590909090909091, td_int_ratio=5.2),
 Row(player_display_name='Tom Brady', season=2015, sum(completions)=402, sum(attempts)=624, sum(passing_yards)=4770.0, sum(passing_tds)=36, sum(interceptions)=7.0, avg(completions)=25.125, avg(attempts)=39.0, avg(passing_yards)=298.125, avg(passing_tds)=2.25, avg(interceptions)=0.4375, completion_percentage=0.6442307692307693, td_int_ratio=5.142857142857143),
 Row(player_display_name='Jeff Garcia', season=2006, sum(completions)=116, sum(attempts)=188, sum(passing_yards)=1309.0, sum(passing_tds)=10, sum(interceptions)=2.0, avg(completions)=14.5, avg(attempts)=23.5, avg(passing_yards)=163.625, avg(passing_tds)=1.25, avg(interceptions)=0.25, completion_percentage=0.6170212765957447, td_int_ratio=5.0),
 Row(player_display_name='Matt Ryan', season=2018, sum(completions)=422, sum(attempts)=608, sum(passing_yards)=4924.0, sum(passing_tds)=35, sum(interceptions)=7.0, avg(completions)=26.375, avg(attempts)=38.0, avg(passing_yards)=307.75, avg(passing_tds)=2.1875, avg(interceptions)=0.4375, completion_percentage=0.694078947368421, td_int_ratio=5.0),
 Row(player_display_name='Russell Wilson', season=2018, sum(completions)=280, sum(attempts)=427, sum(passing_yards)=3448.0, sum(passing_tds)=35, sum(interceptions)=7.0, avg(completions)=17.5, avg(attempts)=26.6875, avg(passing_yards)=215.5, avg(passing_tds)=2.1875, avg(interceptions)=0.4375, completion_percentage=0.6557377049180327, td_int_ratio=5.0),
 Row(player_display_name='Geno Smith', season=2021, sum(completions)=65, sum(attempts)=95, sum(passing_yards)=702.0, sum(passing_tds)=5, sum(interceptions)=1.0, avg(completions)=16.25, avg(attempts)=23.75, avg(passing_yards)=175.5, avg(passing_tds)=1.25, avg(interceptions)=0.25, completion_percentage=0.6842105263157895, td_int_ratio=5.0),
 Row(player_display_name='Aaron Rodgers', season=2012, sum(completions)=371, sum(attempts)=552, sum(passing_yards)=4295.0, sum(passing_tds)=39, sum(interceptions)=8.0, avg(completions)=23.1875, avg(attempts)=34.5, avg(passing_yards)=268.4375, avg(passing_tds)=2.4375, avg(interceptions)=0.5, completion_percentage=0.6721014492753623, td_int_ratio=4.875),
 Row(player_display_name='Ryan Tannehill', season=2020, sum(completions)=315, sum(attempts)=481, sum(passing_yards)=3819.0, sum(passing_tds)=34, sum(interceptions)=7.0, avg(completions)=19.6875, avg(attempts)=30.0625, avg(passing_yards)=238.6875, avg(passing_tds)=2.125, avg(interceptions)=0.4375, completion_percentage=0.6548856548856549, td_int_ratio=4.857142857142857),
 Row(player_display_name='Brett Favre', season=2009, sum(completions)=364, sum(attempts)=532, sum(passing_yards)=4202.0, sum(passing_tds)=33, sum(interceptions)=7.0, avg(completions)=22.75, avg(attempts)=33.25, avg(passing_yards)=262.625, avg(passing_tds)=2.0625, avg(interceptions)=0.4375, completion_percentage=0.6842105263157895, td_int_ratio=4.714285714285714),
 Row(player_display_name='Carson Wentz', season=2017, sum(completions)=265, sum(attempts)=440, sum(passing_yards)=3296.0, sum(passing_tds)=33, sum(interceptions)=7.0, avg(completions)=20.384615384615383, avg(attempts)=33.84615384615385, avg(passing_yards)=253.53846153846155, avg(passing_tds)=2.5384615384615383, avg(interceptions)=0.5384615384615384, completion_percentage=0.6022727272727273, td_int_ratio=4.714285714285714),
 Row(player_display_name='Deshaun Watson', season=2020, sum(completions)=382, sum(attempts)=544, sum(passing_yards)=4823.0, sum(passing_tds)=33, sum(interceptions)=7.0, avg(completions)=23.875, avg(attempts)=34.0, avg(passing_yards)=301.4375, avg(passing_tds)=2.0625, avg(interceptions)=0.4375, completion_percentage=0.7022058823529411, td_int_ratio=4.714285714285714),
 Row(player_display_name='Kirk Cousins', season=2021, sum(completions)=372, sum(attempts)=561, sum(passing_yards)=4221.0, sum(passing_tds)=33, sum(interceptions)=7.0, avg(completions)=23.25, avg(attempts)=35.0625, avg(passing_yards)=263.8125, avg(passing_tds)=2.0625, avg(interceptions)=0.4375, completion_percentage=0.6631016042780749, td_int_ratio=4.714285714285714),
 Row(player_display_name='Derek Carr', season=2016, sum(completions)=357, sum(attempts)=560, sum(passing_yards)=3937.0, sum(passing_tds)=28, sum(interceptions)=6.0, avg(completions)=23.8, avg(attempts)=37.333333333333336, avg(passing_yards)=262.46666666666664, avg(passing_tds)=1.8666666666666667, avg(interceptions)=0.4, completion_percentage=0.6375, td_int_ratio=4.666666666666667),
 Row(player_display_name='Jameis Winston', season=2021, sum(completions)=95, sum(attempts)=161, sum(passing_yards)=1170.0, sum(passing_tds)=14, sum(interceptions)=3.0, avg(completions)=13.571428571428571, avg(attempts)=23.0, avg(passing_yards)=167.14285714285714, avg(passing_tds)=2.0, avg(interceptions)=0.42857142857142855, completion_percentage=0.5900621118012422, td_int_ratio=4.666666666666667),
 Row(player_display_name='C.J. Stroud', season=2023, sum(completions)=319, sum(attempts)=499, sum(passing_yards)=4108.0, sum(passing_tds)=23, sum(interceptions)=5.0, avg(completions)=21.266666666666666, avg(attempts)=33.266666666666666, avg(passing_yards)=273.8666666666667, avg(passing_tds)=1.5333333333333334, avg(interceptions)=0.3333333333333333, completion_percentage=0.6392785571142284, td_int_ratio=4.6)]

I think that does it! Thanks for hainging in there!